import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `H2b`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_H2b.json.gz` (SHA-256 `8738119d54bd5f5611d0089cbc021222afa081a50eba95fbcecb15cbc19ed4df`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1351 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `H2b`. -/
def h2bToks : List String := [
  "r",
  "r",
  "r",
  "xxrrxrr",
  "xxxxxxrrrxrrxxxrrxrrxxrrxrrxxxxrxrrxxrrxrrxxxrxrrxxrrxrrxxxrrxxrrxrrxxxrrxrrxxrrxxrrxrrxlxrrxxxxxrrxrrxxrrxrxrrxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxrrxrrxxrrrxxrrxrrlxrrxxxxxrrrxrrxxrrrxxrrrxxxlrxxrrrxxrrrxxrrrxlrxrrxlrrlrr",
  "xxxxlrrlrrxlrrlrrxlrrlrrxxlrrlrrxlrrlrxrr",
  "xxlrxrlrxrrlrxlrxrrlrrxlxrrxrrlxrrxrr",
  "xxlxrrxrrlxrlrrxlrrxrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrxrr",
  "xxlxlrrlrrxlrxrrlrxrrlxlrrlrrxlrrlrrxxllrrlrrllrrlrxrrxlxxlrrlrrxlrlrrllrxrrxlrrlrrxxlrrlrlrrxlxlrrlrrxlrrlrxrrlxlrrlxrrxrrxlxrrxrrlxrrrlxlxxlrrlrxrrxlxrrxrrlxrrrxxlrxrrlxrrxrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrxrrxxlxlxrrxrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlxrlrrxlrrlrrxlxrlrrxlrrlrrlxlrrlrrxlrrlrr",
  "xxxlxxlxlrxrrlxrlrrxlrrlrrxlxrlrrxlrrlrrlxlrrlrrxlrrrlxlxlrrlrrxlrrrlxrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrlrrlxlrrlrrxlrrlrrxxlxlxlrrlrrxlrrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxlxlrrlrrxlrrlrxrrlxlxrrxrrlxrrxrrxlxrrxrrlrrxlxlrrlrrxlrrlrrlxlrrlxrrxrrxlxrrxrrlxrrxrrxxlxlrrlxrrxrrxlxrrxrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlxrrxrrlrrxlxrrrxlrrlrrxlxlxxlxrrrlrrxlrrlxrrrxxlrrlrrxlrrlrrlxxlrrlrrxlxrrrlrrxxlrrlrrxlrrlrrxxlxlrrxlrrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxxlxrrxrrlxrrxrrxlxrrxrrlrrxxlxrrxrrlxrrxrrxlxrrrlrrlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlrrlrrxlrrlrrlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxxlxrxrrxrxrrlxxrrxrrxxrrxrrxlxxrrrxxrrrlxrrxrrxxlxrxrrxrxrrlxxrrxrrxxrrxrrxlxxrrxrrxxrrxrrxlrrlrrxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrxrrlxxxlrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlrxrrxxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxxlrrlrrlxrrxrrxlxrrxrrlxrrxrrlxxlxrrxrrlrrxlrrlrrxxlxrrxrrlrrxlrrxlrrlrrxxlxxlrrlrrlxrrxrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlxlrrlrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxlxxlrrlrrlrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxlxlrrrxlrrlrrlxrrxlrrlrrxlxrrxrrlxrrxrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrrxlrrrllrrlrr",
  "xxxlxlxrrxrrlxrrxrrxlxlrrrxlrrlrrlxrrxlrrrlxlxrrxrrxlrrlrrxlxrrxrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxlxrrxrrlxrrxrrxxlrrlrrlxrrxrrxlxlxrrxrrlrxrrxlxrrxrrlxrrxrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrr",
  "xxxxllrrlrrllrrlrrlxlrrlrrxlrrlrrxxllrrlrrllrrlrrxllrrlrrllrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
