import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `H3b`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_H3b.json.gz` (SHA-256 `c300377a2e556a7ed719b15f3e1800871e1092fba6fd3fbf23928449548a577b`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1581 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `H3b`. -/
def h3bToks : List String := [
  "r",
  "r",
  "r",
  "xxrrxrr",
  "xxxxxxrrrxrrxxxrrxrrxxrrxrrxxxxrxrrxxrrxrrxxxrxrrxxrrxrrxxxrxrrxxrrxrrxxxrrxrrxxrxrrxxrrxrrxxxxxxxrrxrrxxrrxrrxxxrrxrxrrxxxrrxrrxxrrxrrxxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxrrxrrxxrrxrrxxxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxxxrrxrrxxrrxrrxxxrrrxrrxxxrrxrrxxrrxrrxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxrrxrrxxrrxrrxxxrrxrrxrrxxxrrxrrxxrrxrrxxxxxxrrxrrxrrxxrrxrrxxxrrxrrxrrxxxrrxrrxrrxxxlrxxrrrxxrrrxxrrlrrxxlrrlrrxlrrr",
  "xxxxrrxlrrlrrxxlrrlrrlrrxxlrrlrrxlrxrrlxrrxrr",
  "xxxlrrlrrxlrrlrrxlxrrxrrlxlrrlrrxlrrlrr",
  "xxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrxrrlxlrrlrxrrxlxrrxrrlxrrxrr",
  "xxlxlrxrrlxrrxrrxlxrrxrrlxrrxrrlxlrrlrrxlxrrxrrlrlrrxxllxrrrlrxrrlxlrrxlrrlrrxlrrxlrrlrlrrxlxxlrlrrllxrrxrrxlrxrrlxrrlrrxlxlxrrxrrlxrrxrrxlxrrlrrlxrrrlxlxrrrlrrxlrrlrrxxllxrlrrxrlrrxllrrxlrrlrrllrrxlrrlrrlxllrrlrrllrrlrrxlxlrrlrrxlrrlrrlxlrrrxrrxlxllrrxrrlrrxlxrrxrrlxrrxrrlxlrrlrrxlxrrxrrlxrrxrrlxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrxrrxlrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxlrrlrrxlrxrrlrxrrlxlrrlrrxlrxrrlxrrxlrrxrrxlxlxrlrrxrrlxrrxrrxlxlrrrxxrrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrxlrrlrr",
  "xxxlxxlxlxrrxrrlxrrrxlxrrxrrlxrrrlxlxrrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlxrrxrrxxlxlxrrxrrlrrxxlrrlrrxlrrlrrlxxlrrlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlxrrxrrxlxrrxrrlxrrxrrlxxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlrrlrxrrxlrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxlxrrxrrlrrxlxrrxrrxlrrlrrlxlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrrxxlrrlrrxrrxlxxlxxlrrlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlxrrxrrxlrrlxrrxrrxxlxxrrlrrxxrrxrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxxlxrrxrrlxrrxrrxlrrlrrxxlxrrxrrlrrxlrrlrrlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxxlxrrxrrlrrxlrrlrrxxlxrrxrrlrrxlrrlrrlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlxrrxrrxlrxrrlrxrrxxlrrlxrrxrrxlxrrxrrlxrrxrrlxxlxrrxrrlrrxlrrlrrxxlxrrxrrlxrrxrrxlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxxlxrrxrrxlrrlrrxxlrrlrrxlrrlrrxxlxrrxrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlxrrxrrxlxrrxrrlxrrxrrxxlrrlxrrrxlxrrxrrlxrrxrrlxxlxrrxrrlxrrxrrxlxrrxrrlrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxxlrrlrrxlrrlrrxxlrxrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlxxlrrlrrlrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxlxxlrrlrrlrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxrrlrrxxrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrrlxxrrlrrxxrrxrr",
  "xxxlxlxrrxlrrlrrlxrrxlrrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxrrxrrxlrrlrrxlxlrrlrrxlrrlrrxllrrlrrllrrlrrxlxxlrrlrrxlrrlrrxxlrlrrlrlrrxxlrrlrrxlrrlrrlxxlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxxxlrrlrrxlrrlrrxxlrrlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrlrrlxxlrrlrrlxrrxrrxlxrrxrrlxrrxrrxlxlrrlxrrrxlrxrrlrrxlxlrrlrrxlrrlrrxllrrlrrllrrlrr",
  "xxxxllrrlrrllrrlrrlxlrrlrrxlrrlrrxxllrrlrrllrrlrrxllrrlrrllrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
