import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `H4b`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_H4b.json.gz` (SHA-256 `5b8ce78ba93dba015d927257bc0ca54c18e39afd85f4390c7efabf551974fac4`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1729 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `H4b`. -/
def h4bToks : List String := [
  "r",
  "r",
  "r",
  "xxrrxrr",
  "xxxxxrrxrrxxrxrrxxrrxrrxxxxrrxrxrrxxxrrxrxrrxxxrrxrrxxrrxxrrxrrxxxxxxrrxrrxxrrxxrrxrrxxxxrrxrrxxrrxrrxxxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxrrxrrxxrrxrrxxxxxxrrxrrxxrrrxxrrxrrxxxrrxrrxrrxxxrrxrrxrrxxxxxxrrrxrrxxrrrxxrrrxxrrxrr",
  "xxxxrrxrrxxrrxrrxxxrlrrxlrrlrrxlrxrrxlrrlrr",
  "xxxlxrrxlrrlrrlxrrxrrxlxrrxrrllrrlrrxxllrrlrrllrrlrrxllrrlrrllrrlrr",
  "xxlxxrrxrrxlrrlxrrxrrlxxrrxrrxlxrrxrrlxrrxrrxlxxlrrlrrxlrrlrrxlxrrxrrlxrrxxrrxrrxlxlrrlrrlxrrxxrrrlxlrrlrrxlrrlrxrr",
  "xxlxlxrrxrrlxrrxrrxlxrxrrxxrrxrrlxrrxrrxllrrlxrrxrrllrrlxrrxrrxxllxrrxrrlxrrxlrrlrrxllxrrxrlrrxlrrxlrrlrrlxlrlrrxlrlrrllrxrlrrlxlrrlrrxlrrlrrxxlrrllrrlrxrlrrxllxrlrrxlrrlrxrrlxlrrlxrrxrrxlxrrxrlrrlxrrxlrrxrrllxlrrlrrxlrxrrlrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxxllxlrrlrrxlrrlrrlxlrrlrrxlrrlrrllxlrrlrrxlrrlrrlxlrrrxlrrlrrlxlxrrxrrlxrrxrrxlxrrxlrrlrrlxrrxrrxxllxlrrlrrxlrrlrrlxlrxrrlrrxlxrrxrrlxrrxrrllxlrrlrrxlrrlrrlxlrrlrrxlxrrxrrlrxrrxllxlrrlrrxlrrlrrlxlrrlrrxlrxrrxlrrlrrllxlrrlrrxlrrlrrlxxrrxrrxxlrrlrrxlrrlrrlxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxllxrrxrrlxrrxrrllxrrxrrlxrrxrrxxllxlrrlrrxlrrlrrlxxrrxrrxxlrrlrrxlrrlrrllxrrxxrrxrrlxxrrxrrxxlrrlrrxlrrrxllxrrxxrrxrrlxxrrxrrxxrrxrrlxlrrlrrxlxrrxrrlxrrrxxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrr",
  "xxxxlxxllrrxlrrrlxrrxrrxlxrrxrrllrrlrrxxlxlrrlrrxlrrlrrlxrrxlrrlrrxlxrrxlrrrlxrrxrrlxxllrrxrlrrlxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxlxxlrrlrrlrrxxlrrlrrrlxrrxrrxxlxlrrrxrrlrrxlrrlrrxxlxlxrrxrrxlxrrrlxrrxrrxxlrrlrrlxrrxrrllxxxrrxrrxxrrxlrrlrrxxxrrxrrxxrrxlrrlrrlxxxrrxrrxxrrxlrrlrrxxxrrxrrxxrrxlrrlrrlxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxlrrxlrrlrrlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxxlrrlrrxlrrlrrxlrrxlrrlrrxxxlrrlrrxlrrlrrxlrrxlrrlrrlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxlxxxlrrlrrxlrrlrrxxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxxlrrlrrxlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrlrrxxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrxlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxxlrrlrrlrrxlrrlrrxxxlrrlrrlrrxlrrlrrlxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrxrrxxrrxrrxxxrrxrrxxrrxrrxxlxxrrxrrxxrrxrrlxxrrxrrxxrrxrrxlxxrrlrrxxrrxrrlxrrxrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrxlrrlrrlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxrrrxxlrrrrxlxxxlrrlrrxlrrlrrxxlrrlrrlxrrxrxrrxxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlrrxxlrrlrrxlrrlrrlxlrrxlrrlrrxxlrrlrrxlrrlrr",
  "xxxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxlrrlrrxlrlrrlrlrrlxlrrlrrxlrlrrlrrxxlxlrrxlrrlrrxlrrxlrrlrrxlxlrrlrrxlrrlrrllrrlrrxxllrrlrrllrrlrrxllrrlrrllrrlrrxxxxllrrlrrllrrlrrxllrrlrrllrrlrrxxllrrlrrllrrlrrlxlrrlrrxlrrlrrxxxllrrlrrllrrlrrlxlrrlrrxlrrlrrxlxlrrrxlrrrlxrrxrr",
  "xxxxlrrlrrlxrrxrrxxlrrlrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxxrrxrlrrxrxrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
