import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `H8`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_H8.json.gz` (SHA-256 `200c5b76c6f36b130149efb986b4ae0980d416fd50e738a7a27a3836389600dd`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1611 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `H8`. -/
def h8Toks : List String := [
  "r",
  "r",
  "r",
  "xxrrxrr",
  "xxxxxrrxrrxxrrxrrxxxrxrrxxrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrrxrrxxxxxrrrxrrxrrxxrrxrr",
  "xxxrxrrxxrrxrrxxxxrrxrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrlrrlxrrlrr",
  "xxxxxlxrrlrrlxrrrxlrrlrlrrxlxlrrlrrlrrlxlrrlrrxlrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxxlxlrrlrrxlrrlrrllxrrxrrxlrrlrrxllrrxlrrlrrllrrxlrrlrrxxllrrlrrllrrlrlrrxllrrlrlrrlxrrxlrrlrr",
  "xxxxlxrrxlrrlrrlxrrxlrrlrrxllrrlrlrrllrrlrlrrxxlxrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlxrrxrrxxxlxlrrlrrxlxrrxlrrlrrlxrrxlrrlrrlxlrrlrrxlxrrxlrrlrrlxrrxlrrlrrxlxlrrlrxrrxlxrrxlrrlrrlxrrxlrrlrrlxlrrlrrxlxrrxlrrrlxrrxrrxxlxlrrlrrxlrxrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrr",
  "xxxxlxlrrlrrxlrrlrrlxlrrrxlrrrlxxrrlrrxxrrlrrxlxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxlrrlrrxxlxxlrrlrrlxrrxrrxlxrrxrrlxrrxrrxxlllrrlrrllrrlrrxllrrlrrllrlrrllrrlrrxxlllrrlrrlxrlrrxlrrlxrlrrxrlrxrrllxlrrlxrlrrxrlrxrrxlrxrlrrlxlrrlxrrxrrxlxrrxrrlxrrxrrlxlxrlrxrrxlrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxlxlrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrrxlxrrxrrlrrxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlrrxlxrrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlxrrxrrlxrrxrrxlxrrxrrlxrrrlxlrrlrrxlrrlrrxlxlxrrxrrlrrxlxrrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrxrrlxrrrlxlrrlrrxlrrlrrxxxlxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxllxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrrlxlxlrrlrrxlrrlrrlxlrrrxrrxlxlrrrxlrrrlxrrrllxlxlrrrxlrrrlxrrrxlxrrxrrlrrxllrrlrrllrrlrrxxlxllrrlrrllrrlrrxllrrlrrllrrlrrlxllrrlrrllrrlrrxllrrlrrllrrlrrxlxllrrlrrllrrlrrxllrrlrrllrrlrrlxllrrlrrllrrlrrxllrrlrrllrrlrrxxxlxllrrlrrllrrlrrxllrrlrrllrrlrrlxlrrlrrxllrrxrrlrxrrxlxlrrlrrxlrxrrlrrlxlrrlrrxlrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlxrrxrlrrxlxlxrrxrrlxrrxrrlxxrrxrrxxrrxrrlxlxrrxrrlxrrxrrlxxrrxrrxxrrxrr",
  "xxxxxlxxlxrrxrrlrrxlrrlrrxlxxrrrxxrrrlxrrxrrlxxlrrlrrxlrrlrrxlxrrxrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrxrrlrxrrxlrxrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxxlxlrrlrrxlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrxlrrlrrxxlrrlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrlrrxxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlxxrrxrrxxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxxxrrrxrrxxxrrrxrrxlxrrxrrxlrrxlrrlrr",
  "xxxxlxxrrxrrxxrrxrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrxllrrlrrllrrlrrxxxllrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxxxxxlrrlrrxlrrlrrxllrrrlrrxxlrrlrrlxrrxrrxxxlrrlrrxlrrlrrxxlrrlrrxlrrlrr",
  "xxxxlrrlrrxlrrlrrxxxrrxrrxxrrxrrxxxxrrxrrxxrrxrrxxlrrlrrxlrrlrxrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
