import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `L1`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_L1.json.gz` (SHA-256 `44b650091f2fbb301facfc941e26513a9dfc15f9bb3939510fc9aea0de634102`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1177 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `L1`. -/
def l1Toks : List String := [
  "r",
  "r",
  "r",
  "xrr",
  "xxxxrrxrrxrrxxrrr",
  "xxrrxrr",
  "xxrxrrxxrlrrxlrrlrr",
  "xxxlrrlrrxlrrlrrxxlxrrxrrlxrrxrrxlxlrrlrrxlrrlrrxllrrlxrrxrrlxlrrlrxrrxlrrlxrrr",
  "xxxlxlxrrxrrlxrrrxlxrrxrrxlrrrxlxrrxrrlxrrxrrxlxxrrrxrrlrrxxllrrlrrllrrlrrxllrrlrrlxrlrrxrr",
  "xxxllrrlrrxlrrlrrxllrrlrrllrrlrrxxllrrlrrxllrrlrrllrrxlrrlxrlrrxlrxrrlxrlrrxlrrlrrxxlxlrxlrrlrxrlrrlxlrxrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrrxrlrrlxlxlrrlrrxrlrrlxlrrlxrrxrrxlxrrxrlrrlxrrxrrxlxlrrlxrrxrrxlxrrxrrlxrrxrrlxlxlrrrxrrlrrxlrrrlxlxlxlrrlrrxlrrrlxlrrlrxrrxlrxrrlxrrxrlrrxlxlrrlrxrrxlxrrxrrlxrlrrxlrrrlxlxrlrrxlrrrlxlrrrxrrxlxrrrrlxlxlxrrxrlrrlxlrrlrrxrrxlxlrrrxrrlrrlxlxrrrrxlrrlrxrrxlxlrrlrrxlrrlxrrrlxlxrrxrrlrrxlrrlrrxlxlxlxrlrrxlrrrlxrrrxlxrrrrlxrlrrxlrrlrrxlxrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlxrrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrrxrlrrlxlrrlrrxlrrrxlxlxlxlrxrrlxrrrxlxrrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxrrxrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrrxrrlxlrrlrrxlrrlrrlxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxllxlrrlrrxlrrlrrlxlrrlrrxlrrrxlllrrlrrllrrrlllrrxrrlxrrxlrrlrrxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxxllrrrlrrlxrrxrrlxlxrrxrxrlrrlxxrlrrxlrrlrrxxlrrlrrxlrrlrrxlxrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrr",
  "xxxxlxlxlxlrrlrrxxrrxlrrlrrlxxlrrlrrlxrxrrxxrrxrrxxlrrlxrrxrrlxxrrxrrxxrrrxlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlxrrrlxrrrxlrrlrrxxlrrlrrxlrrrlxlxlxxrrxrrxxrrrlrrxxlrrlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxlxlxxlrrlrrxlrrlrrxxlrrlrrxlrrrlxxlrrrlrrxlrrrxlxxlrrlrrrxrrlxrrxrrlxlxlrrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxlxlrrrxrrlxrrxrrlxlxlrrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrrlrrxlxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrrxlxlxrrrlxrrrxlrrlrrlxlrrlrrxlrrlrrlxlxlxrrxrrlxrrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrrlxlrrrxrrlxlxlrrlrrxlrrrlxlrrlrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrlxrrrlxlxrrxrrlxrrrxlrrlrrxxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrxllrrlrrllrrlrrxxxllrrlrrllrrlrrxllrrlrrllrrrxxllrrrllrrrxllrrrllrrr",
  "xxxxllrrlrrllrrrxlrrlrrxxlrrlrrlxrrxrrxxxlrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrrxlxrrrlrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
