import Erdos993Lean.Analytic.O2.Cert.Compute.DataGap

/-!
# O2 certificate checker (lane A18): the cover of the gap row `L23`

Campaign `ProofRuns/2026-09-28_analytic_large_n`, lane A18.  Converted by `LEAN/lanes/A18/scratch/gen_gaps.py` from
`LEAN/o2_gaps/certs/tight_cert_L23.json.gz` (SHA-256 `657c2304a5401c2ba75d9d3b034d3b702b44da3428f2de131f1448b61c59d80d`) to one preorder string per root box
(`'l'`/`'x'`: split `λ`/`x`, lower half first; `'r'`: a leaf): 1883 leaves.  The soundness of the walk does not depend
on these data.
-/

namespace Erdos993Lean.Analytic.O2.Cert.Compute

/-- The twelve root covers of the gap row `L23`. -/
def l23Toks : List String := [
  "r",
  "r",
  "r",
  "xrr",
  "xxxxrrxrrxxrrxrrxxrrxlrrr",
  "xxxrrxrrxxrrxrlrr",
  "xxxrlrrxlrrlrrxxlrrlrrxlrrlrr",
  "xxxlrrlxrrrxlxrrxrrlxlrrlrrxrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrxrrxlxlxrrxrrlxrlrrxlrrlrrxlxrrxrrlxrrxrrlxlxlrrlrrxlrrlrrlxlrrxlrrlrrxlrrxlrrlrrxlxrrxrrxllrrlrrlxrlrrxrlrr",
  "xxxlxlxlrrlrrxlrrlrrlxrrxrrxlxxrrrxxrrrlxrrxrrlxlxrrxrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxxllrrlrrllxrrrlrrxlllrrrlrrxllrrlrrllxrrrlrr",
  "xxxllxrrrlrrllxrrxrrlxrrrxllxrrxrrlxrrxrrllxrrxrrlxrrxrrxxlxlrrllrrlrrxllrrlrrlxrlrxrlrrxlrxrlrrlxlrrlxrrxrrxlxrrxrrlxrrxrrlxlxlrrlrrxlrxrlrrlxrlrxrrxlxrrxrrlxrrxrrlxlxrlrxrrxlrxrrlxrlrrxlrrlrrlxlxrlrrxlrrlrrlxlrrlrrxlrrrxlxlrrrxrrlxrlrrxlrrlrxrrxlxlxrlrrxrlrrlxlrrrxrrxlxlrrrxrrlxrlrrxlrrlrxrrlxlxrlrrxlrrlrxrrlxlrxrrlxrrxrrxlxrrrlrrxlxlrxrrlxrrrxlxrrrlrrlxlrrrrxlxlxlrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrrlxrlrrxlrrlrrxlxlxrrxrrlxrrrxlxrrrlxrlrrxlrrxrrlxlxrlrrxlrrlrrxllrrxlrrlrrllxrrrxrrxxllrrxlrrrlxlrrrxrrxlxrrrlrrlxlxlxrlrrxlrrlrrlxlrrlxrrrxlxrrrlrrxlxlrrlxrrrxlxrrrxlrrrlxlrrrrlxlxlrrrrlxrlrrxlrrxrrxlxrxrrxxrrxrrxlxrrxrrlxrrrxxllxxrrrrxlrrlrxrrllxrxrrxrxrrxlxrrrlrrlxxlxrrrlxrrrxlrrlrrxxlrrlrrxlrrlrrxlxlxlxlxlrrrxlrrlrxrrlxlrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlrxrrlxrrxrrxlxrrxrrlrrlxlxrrrrrlxlxlxrrxrrlrrxlrrrlxrlrrxlrrlrrxlxrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlrrrrlxrlrrxlrrlrrxlxrlrrxlrrlrrlxlrrlrrxxrrxrrlxlxlrrlrrxlrrlrrlxlrrrrxlxxrrrrxlrxrrlxrrrlxlxlxlrrlrrxlrrlrrlxlrrrxrlrrxlxlrrrxrlrrlxlrrlrrxxrrrlxlxlrrlrrxlrrrlxrlrrxrxrrxlxrrxrrxlxrrrlrxrrxlxlxxrrxrrxxrrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlxlxlrrxrrxxrrrlxxrrxrrxxrrrxxlrrlrrxlrrlxrrrlxxlrxrrlxrrrxlrrlrrxxlrrlrrxlrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrxrrxlxrrxrrlxrrrlxxlxlrrlrrxlrrlxrrxrrlxlrxrrlxrrxrrxlxrrxrrlrrlxxlxrrrlrxrrxlxrrxrrlxrrrxxlrxrrlxrrxrrxlrxrrlxrrrxxlxlxrrxrrlxrrrxlrrlrrlxlrrlxrrxrrxlxrrxrrlxrrrxlxlxrrrlrxrrxlrrlrrlxlrrlrrxlrrlrrlxlxlxlxxrrxrrxxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxxlxrrxrrlxrrxrrxlxrrrlrrxlxxlxrrxrrlxrrxrrxlxrrrlxrrxrrxxlxrrxrrlrxrrxlxrrxrrlrrlxxlxrrrlrrxlrrlrrxxlrrlrrxlrrlxrlrrxlrrlrrlxlxxlxrrrlrrlxrxrlrrxrxlrrlrrxxlrrlrxrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxllxxlrrlrrxlrrlrrxxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrrrlxlxlrrlrrxlrrrlxrrlrrxlrrlrrxlxxlrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrrlrrxlxlxrrrlrrxlrrlrrllxrrxrrlxrrxrrxlxlxxlxrrxrrlxrrrxlrrlrrxxlrrlrrxlrrlrrxlxlrrlrxrlrrxlrxrlrrlxlrrlrrxlrrlrrlxlxrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxxlxlrrlrrxlrrlrrlxlrrlrxrlrrxlrxrlrrlxlrrlrrxlrrlrrxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrrrlxlxlrrlrrrlrrxlrrlrrxlxlxlxlrrlrrxlrrrlxlrrrrxlrrlrrlxlrrlrrlxrrxrrxlxlrrlrrlrrllrrlrrlxllxrrxrrlxrrrllxrrxrrlrrxllrrlrrllrrlrr",
  "xxxlxlxlxxlrrlrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrrlrrlxlxlxrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrrxlrrlrrxlxlxrrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlxlxrrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxxrrxrrlxlxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxlxlrrlrrxlrrlrrlxlrrlrrxlrrrxlxlrrlrrxrrlxrrxrrxxllxlrrlrrxlrrlrrlxxrrxrrxxrrrllxlrrrxrrlxrrxrrxllxrrxrrlxrrxrrllxrrxrrlxrrxrrxlxlxlxlrrrxrrlxrrxrrxlxrrxrrlxrrxrrlxlxrrxrrlxrrxrrxlxrrrlrrxxllxrrxrrlrrllxrrrlrrxllrrlrrllrrlrrlxxllxrrrlrrllrrlrrxllrrlrrllrrlrrxxllrrlrrllrrlrrlxlrrlrrxlrrlrrxxxlxllrrlrrllrrlrrxllrrlrrllrrlrrllxlrrlrrxlrrlrrlxlrrlrrxrrlxxllrrlrrllrrlrrxllrrlrrllrrrxxlrrlrrxlrrlrrxlxxllrrrlrrxlrrlrrxxlrrlrrxlrrlrrlxxlrrlrrlxrrxrrxxlrrlrrlrr",
  "xxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrxxlxlrrlrrxlrrlrrlxlrrlrrxlrrlrrlxxlrrlrrxlrrlrrxxlrrlrrxlrrlrr"
]

end Erdos993Lean.Analytic.O2.Cert.Compute
