import Mathlib
import Erdos993Lean.Zhang.Relaxation
import Erdos993LeanZhangCompute.Checker

/-!
# Zhang's finite-part certificates: from the Boolean checks to `NoRecovery`

The computable definitions (`Erdos993LeanZhangCompute/Checker/Core.lean` and
`Erdos993LeanZhangCompute/Checker.lean`, namespace `Erdos993Lean.ZhangCertX`) check T. Zhang's
certificates for the finite part (*Exact Certificates for Unimodality of Forest Independence
Polynomials*, v1.1, Sections 2.7–2.10).  This file proves, with the standard axioms only, that a
passing check gives the certificate layer's claim `Cert.NoRecovery` of
`Erdos993Lean/Zhang/Relaxation.lean`:

* `binomN_eq`: the table-and-formula binomial is `Nat.choose`; `binomZ_cast`: `binomZ` is the
  paper's binomial `Cert.binom`.
* `BZ_cast`, `bStepZ_cast`, `sExtZ_cast`, `UZ_cast`, `VtZ_cast`, `βZ_cast`, `C0Z_cast`,
  `GrZ_cast`: the integer mirrors of `Cert.B`, `Cert.bStep`, `Cert.sExt`, `Cert.U`, `Cert.Vt`,
  `Cert.β`, `Cert.C0`, `Cert.Gr`.
* `toRow n a ℓ`: the row of `Relaxation.lean` named by the label `ℓ` (`Cert.Label.row` for the
  eleven families, `Cert.assumptionRow` for `assumption(k)`); **`coefZ_cast`, `rhsZ_cast`**: the
  checker's coefficients and right sides are exactly those of `toRow` (every label, every `(j, m)`).
* `coefZ_eq_zero`: `coefZ` vanishes off the layers flagged by `touches` (so the checker may skip
  the other rows layer by layer).
* `toRow_holds`: a row accepted by `rowOKB` holds for every feasible array (`Cert.Feasible`) with
  `Δ_k ≤ 0` (the family rows on their domains `Cert.Label.InDomain`, `assumption(k)` by
  `Cert.assumptionRow_holds`).
* `aggRow`, `aggRow_holds`: the weighted sum `Σ w_ρ · row ρ` of accepted rows (natural weights)
  holds.
* **`genericOK_sound`**: `genericOK n a k kind σ rows = true → Cert.NoRecovery n a k`, for every
  kind, target scale `σ` and weighted row list: the certificate principle
  `Cert.certificate_bound` (Zhang's (40)) applied to the single aggregated row (scale `1`,
  multiplier `1`), the target `σ·(−B(k))` (`pos`) or `σ·B(k + 1)` (`neg`, `cond`), the constant `η`
  and the layer maxima `M_j` computed by the checker (`target_eq` identifies the target with `−Δ_k`
  or `Δ_{k+1}`, `Cert.delta`).
* `tripleOK_sound`, **`checkN_sound`**, **`checkRange_sound`**: the checks of a triple (with any
  stored data), of an order `n` (with any data string: the domain `(a, k)` at `n` is regenerated by
  the checker and identified with `Cert.InP60` here) and of a range of orders.

No `sorry`, `native_decide`, `axiom`, `unsafe`, `implemented_by` or `extern` here.  The checks
themselves are in `ZhangCert/Checks.lean`; the assembly is `ZhangCert/Main.lean`.
-/

namespace Erdos993Lean

namespace ZhangCertX

open Erdos993Lean.Zhang.Cert Finset

/-! ### Binomial coefficients -/

/-- `descF` is the falling factorial `Nat.descFactorial`. -/
theorem descF_eq (n k : ℕ) : descF n k = n.descFactorial k := by
  induction k with
  | zero => rfl
  | succ k ih => rw [descF, ih, Nat.descFactorial_succ]

/-- `factN` is the factorial. -/
theorem factN_eq (k : ℕ) : factN k = k.factorial := by
  induction k with
  | zero => rfl
  | succ k ih => rw [factN, ih, Nat.factorial_succ]

/-- The falling-factorial formula computes `Nat.choose`. -/
theorem binomF_eq (n k : ℕ) : binomF n k = n.choose k := by
  rw [binomF, descF_eq, factN_eq, Nat.choose_eq_descFactorial_div_factorial]

/-- The table entries are the formula values. -/
theorem binomTab_getD {n k : ℕ} (hn : n < 64) (hk : k < 64) :
    (binomTab.getD n #[]).getD k 0 = binomF n k := by
  have h1 : binomTab.getD n #[] = Array.ofFn (n := 64) (fun j => binomF n j.val) := by
    unfold Array.getD
    rw [dif_pos (by simp [binomTab, hn])]
    simp [binomTab]
  rw [h1]
  unfold Array.getD
  rw [dif_pos (by simp [hk])]
  simp

/-- **The checker's binomial is `Nat.choose`.** -/
theorem binomN_eq (n k : ℕ) : binomN n k = n.choose k := by
  unfold binomN
  split_ifs with h
  · rw [binomTab_getD h.1 h.2, binomF_eq]
  · exact binomF_eq n k

/-- **`binomZ` is the paper's binomial `Cert.binom`.** -/
theorem binomZ_cast (b r : ℤ) : ((binomZ b r : ℤ) : ℚ) = binom b r := by
  unfold binomZ binom
  split_ifs <;> simp [binomN_eq]

/-- `posZ` is `Cert.pos`. -/
theorem posZ_cast (x : ℤ) : ((posZ x : ℤ) : ℚ) = pos x := rfl

/-! ### Parameters and the auxiliary functions of the rows -/

/-- The checker's parameters are those of `Relaxation.lean` (by definition). -/
theorem vP_eq (n a : ℕ) : vP n a = v n a := rfl
theorem δP_eq (n a : ℕ) : δP n a = δ n a := rfl
theorem EP_eq (n a : ℕ) : EP n a = E n a := rfl
theorem D0P_eq (n a : ℕ) : D0P n a = D0 n a := rfl
theorem hallCZ_eq (n a r l : ℕ) : hallCZ n a r l = hallC n a r l := rfl

/-- `BZ` is `Cert.B`. -/
theorem BZ_cast (m j k : ℕ) : ((BZ m j k : ℤ) : ℚ) = B m j k := by
  simp only [BZ, B, Int.cast_sub, binomZ_cast]

/-- `bStepZ` is `Cert.bStep`. -/
theorem bStepZ_cast (a r h m : ℕ) : ((bStepZ a r h m : ℤ) : ℚ) = bStep a r h m := by
  unfold bStepZ bStep
  split_ifs <;> simp

/-- `sExtZ` is `Cert.sExt`. -/
theorem sExtZ_cast (n a r : ℕ) : ((sExtZ n a r : ℤ) : ℚ) = sExt n a r := rfl

/-- `UZ` is `Cert.U`. -/
theorem UZ_cast (a r h m : ℕ) : ((UZ a r h m : ℤ) : ℚ) = U a r h m := by
  unfold UZ U
  simp only
  split_ifs <;> simp only [Int.cast_add, Int.cast_mul, Int.cast_natCast, posZ_cast, Int.cast_zero]

/-- `VtZ` is `Cert.Vt`. -/
theorem VtZ_cast (a r h m : ℕ) : ((VtZ a r h m : ℤ) : ℚ) = Vt a r h m := by
  unfold VtZ Vt
  simp only
  split_ifs <;> simp only [Int.cast_natCast, Int.cast_zero]

/-- `βZ` is `Cert.β`. -/
theorem βZ_cast (n a r : ℕ) : ((βZ n a r : ℤ) : ℚ) = β n a r := by
  simp only [βZ, β, Int.cast_sub, Int.cast_mul, binomZ_cast, vP_eq, Int.cast_natCast,
    Int.cast_ofNat]

/-- `C0Z` is `Cert.C0`. -/
theorem C0Z_cast (n a r : ℕ) : ((C0Z n a r : ℤ) : ℚ) = C0 n a r := by
  simp only [C0Z, C0, Int.cast_add, Int.cast_mul, binomZ_cast, vP_eq, δP_eq, Int.cast_natCast,
    Int.cast_one]

/-- `GrZ` is `Cert.Gr`. -/
theorem GrZ_cast (n a r : ℕ) : ((GrZ n a r : ℤ) : ℚ) = Gr n a r := by
  simp only [GrZ, Gr, Int.cast_sub, binomZ_cast, vP_eq, D0P_eq]


/-! ### Rows -/

/-- The row of `Relaxation.lean` named by a label. -/
def toRow (n a : ℕ) : CLabel → Row
  | .count r => (Label.count r).row n a
  | .path r => (Label.path r).row n a
  | .priv r h => (Label.priv r h).row n a
  | .hall r l => (Label.hall r l).row n a
  | .tail r h => (Label.tail r h).row n a
  | .releaseUpper r h => (Label.releaseUpper r h).row n a
  | .tailUpper r h => (Label.tailUpper r h).row n a
  | .mean r => (Label.mean r).row n a
  | .union r => (Label.union r).row n a
  | .edgeLower r => (Label.edgeLower r).row n a
  | .edgeUpper r => (Label.edgeUpper r).row n a
  | .assumption k => assumptionRow a k

/-- **The checker's coefficients are those of the rows of `Relaxation.lean`**, for every
label and every `(j, m)`. -/
theorem coefZ_cast (n a : ℕ) (ℓ : CLabel) (j m : ℕ) :
    ((coefZ n a ℓ j m : ℤ) : ℚ) = (toRow n a ℓ).coef j m := by
  cases ℓ with
  | count r => simp only [coefZ, toRow, Label.row]; split_ifs <;> simp
  | path r => simp only [coefZ, toRow, Label.row, Int.cast_neg, binomZ_cast]
  | priv r h =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_mul, Int.cast_add, Int.cast_natCast,
      Int.cast_one, Int.cast_zero, posZ_cast, vP_eq]
  | hall r l =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_mul, Int.cast_add, Int.cast_natCast,
      Int.cast_one, Int.cast_zero, binomZ_cast, hallCZ_eq]
  | tail r h =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_add, Int.cast_natCast, Int.cast_one,
      Int.cast_zero, bStepZ_cast, vP_eq]
  | releaseUpper r h =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_mul, Int.cast_zero, sExtZ_cast, posZ_cast,
      UZ_cast]
  | tailUpper r h =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_zero, sExtZ_cast, VtZ_cast]
  | mean r =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_neg, Int.cast_natCast, Int.cast_zero,
      βZ_cast]
  | union r =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_mul, Int.cast_natCast, Int.cast_one,
      Int.cast_zero, binomZ_cast, vP_eq]
  | edgeLower r =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_add, Int.cast_neg, Int.cast_one, Int.cast_zero,
      binomZ_cast, vP_eq]
  | edgeUpper r =>
    simp only [coefZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_sub, Int.cast_natCast, Int.cast_zero, GrZ_cast, D0P_eq]
  | assumption k => simp only [coefZ, toRow, assumptionRow, BZ_cast]

/-- **The checker's right sides are those of the rows of `Relaxation.lean`.** -/
theorem rhsZ_cast (n a : ℕ) (ℓ : CLabel) : ((rhsZ n a ℓ : ℤ) : ℚ) = (toRow n a ℓ).rhs := by
  cases ℓ with
  | count r => simp only [rhsZ, toRow, Label.row, binomZ_cast, vP_eq]
  | path r => simp only [rhsZ, toRow, Label.row, Int.cast_sub, binomZ_cast]
  | priv r h => simp [rhsZ, toRow, Label.row]
  | hall r l =>
    simp only [rhsZ, toRow, Label.row]
    split_ifs <;> simp only [Int.cast_mul, Int.cast_zero, binomZ_cast, hallCZ_eq]
  | tail r h => simp [rhsZ, toRow, Label.row]
  | releaseUpper r h => simp [rhsZ, toRow, Label.row]
  | tailUpper r h => simp [rhsZ, toRow, Label.row]
  | mean r =>
    simp only [rhsZ, toRow, Label.row, Int.cast_sub, Int.cast_neg, Int.cast_mul, C0Z_cast,
      βZ_cast, binomZ_cast, vP_eq]
  | union r => simp [rhsZ, toRow, Label.row]
  | edgeLower r =>
    simp only [rhsZ, toRow, Label.row, Int.cast_add, Int.cast_neg, Int.cast_mul, binomZ_cast,
      vP_eq]
  | edgeUpper r =>
    simp only [rhsZ, toRow, Label.row, Int.cast_sub, Int.cast_mul, Int.cast_natCast, GrZ_cast,
      binomZ_cast, vP_eq, D0P_eq]
  | assumption k => simp only [rhsZ, toRow, assumptionRow, Int.cast_neg, BZ_cast]


/-- `coefZ` vanishes off the layers flagged by `touches`. -/
theorem coefZ_eq_zero {n a : ℕ} {ℓ : CLabel} {j : ℕ} (h : touches ℓ j = false) (m : ℕ) :
    coefZ n a ℓ j m = 0 := by
  cases ℓ with
  | path r => simp [touches] at h
  | assumption k => simp [touches] at h
  | _ =>
    simp only [touches, Bool.or_eq_false_iff, beq_eq_false_iff_ne, ne_eq] at h
    simp [coefZ, h]

/-- A row accepted by `rowOKB` holds for every feasible array with `Δ_k ≤ 0`. -/
theorem toRow_holds {n a k : ℕ} {kind : Kind} {t : ℕ → ℕ → ℚ} (hF : Feasible n a t)
    (hk : delta n a t k ≤ 0) {ℓ : CLabel} (h : rowOKB n a k kind ℓ = true) :
    (toRow n a ℓ).Holds n a t := by
  cases ℓ with
  | count r => exact hF.rows (.count r) (of_decide_eq_true h)
  | path r => exact hF.rows (.path r) (of_decide_eq_true h)
  | priv r h' => exact hF.rows (.priv r h') (of_decide_eq_true h)
  | hall r l => exact hF.rows (.hall r l) (of_decide_eq_true h)
  | tail r h' => exact hF.rows (.tail r h') (of_decide_eq_true h)
  | releaseUpper r h' => exact hF.rows (.releaseUpper r h') (of_decide_eq_true h)
  | tailUpper r h' => exact hF.rows (.tailUpper r h') (of_decide_eq_true h)
  | mean r => exact hF.rows (.mean r) (of_decide_eq_true h)
  | union r => exact hF.rows (.union r) (of_decide_eq_true h)
  | edgeLower r => exact hF.rows (.edgeLower r) (of_decide_eq_true h)
  | edgeUpper r => exact hF.rows (.edgeUpper r) (of_decide_eq_true h)
  | assumption k' =>
    have h' := of_decide_eq_true h
    rw [h'.2]
    exact assumptionRow_holds hk

/-! ### Folds -/

/-- A left fold of additions is a list sum. -/
theorem foldl_add_eq {α : Type*} (f : α → ℤ) (l : List α) (c : ℤ) :
    l.foldl (fun acc x => acc + f x) c = c + (l.map f).sum := by
  induction l generalizing c with
  | nil => simp
  | cons x l ih => rw [List.foldl_cons, ih, List.map_cons, List.sum_cons]; ring

/-- A left fold of maxima bounds its start and every term. -/
theorem foldl_max_ge {α : Type*} (f : α → ℤ) (l : List α) (c : ℤ) :
    c ≤ l.foldl (fun acc x => max acc (f x)) c ∧
      ∀ x ∈ l, f x ≤ l.foldl (fun acc x => max acc (f x)) c := by
  induction l generalizing c with
  | nil => simp
  | cons y l ih =>
    obtain ⟨h1, h2⟩ := ih (max c (f y))
    refine ⟨le_trans (le_max_left _ _) h1, ?_⟩
    intro x hx
    rcases List.mem_cons.mp hx with rfl | hx
    · exact le_trans (le_max_right _ _) h1
    · exact h2 x hx

/-- Filtering out terms that vanish does not change a list sum. -/
theorem sum_filter_eq {α : Type*} (p : α → Bool) (f : α → ℤ) (l : List α)
    (h : ∀ x ∈ l, p x = false → f x = 0) : ((l.filter p).map f).sum = (l.map f).sum := by
  induction l with
  | nil => simp
  | cons x l ih =>
    have ih' := ih (fun y hy => h y (List.mem_cons_of_mem _ hy))
    by_cases hx : p x = true
    · simp [hx, ih']
    · have h0 := h x List.mem_cons_self (by simpa using hx)
      simp [hx, ih', h0]

/-- `rowSum` as a list sum. -/
theorem rowSum_eq (n a : ℕ) (rows : List (CLabel × ℕ)) (j m : ℕ) :
    rowSum n a rows j m = (rows.map fun p => (p.2 : ℤ) * coefZ n a p.1 j m).sum := by
  rw [rowSum, foldl_add_eq, zero_add]

/-- The rows skipped on layer `j` contribute nothing there. -/
theorem rowSum_layerRows (n a : ℕ) (rows : List (CLabel × ℕ)) (j m : ℕ) :
    rowSum n a (layerRows rows j) j m = rowSum n a rows j m := by
  rw [rowSum_eq, rowSum_eq, layerRows]
  apply sum_filter_eq
  intro p _ hp
  rw [coefZ_eq_zero hp, mul_zero]

/-- `rhsSum` as a list sum. -/
theorem rhsSum_eq (n a : ℕ) (rows : List (CLabel × ℕ)) :
    rhsSum n a rows = (rows.map fun p => (p.2 : ℤ) * rhsZ n a p.1).sum := by
  rw [rhsSum, foldl_add_eq, zero_add]

/-- The checker's sum over the layers `1 ≤ j ≤ v` is the sum over `Icc 1 v`. -/
theorem sum_Icc_eq_foldl (f : ℕ → ℤ) (v : ℕ) :
    ∑ j ∈ Icc 1 v, (f j : ℚ) = (((List.range' 1 v).foldl (fun acc j => acc + f j) 0 : ℤ) : ℚ) := by
  rw [foldl_add_eq, zero_add, Int.cast_list_sum, List.map_map]
  induction v with
  | zero => simp
  | succ v ih =>
    rw [Finset.sum_Icc_succ_top (by omega), ih, List.range'_concat, List.map_append,
      List.sum_append]
    simp [add_comm]


/-! ### The aggregated row -/

/-- The weighted sum of a list of rows (weights `w ≥ 0`). -/
def aggRow (n a : ℕ) (rows : List (CLabel × ℕ)) : Row where
  coef j m := (rows.map fun p => (p.2 : ℚ) * (toRow n a p.1).coef j m).sum
  rhs := (rows.map fun p => (p.2 : ℚ) * (toRow n a p.1).rhs).sum

/-- The aggregated row holds when every row of the list holds (the weights are `≥ 0`). -/
theorem aggRow_holds {n a : ℕ} {t : ℕ → ℕ → ℚ} {rows : List (CLabel × ℕ)}
    (h : ∀ p ∈ rows, (toRow n a p.1).Holds n a t) : (aggRow n a rows).Holds n a t := by
  induction rows with
  | nil => simp [aggRow, Row.Holds]
  | cons p rows ih =>
    have hp := h p List.mem_cons_self
    have ih' := ih (fun q hq => h q (List.mem_cons_of_mem _ hq))
    unfold Row.Holds aggRow at *
    simp only [List.map_cons, List.sum_cons] at *
    have hsplit : ∑ q ∈ vars n a, ((p.2 : ℚ) * (toRow n a p.1).coef q.1 q.2 +
        (rows.map fun p => (p.2 : ℚ) * (toRow n a p.1).coef q.1 q.2).sum) * t q.1 q.2 =
        (p.2 : ℚ) * ∑ q ∈ vars n a, (toRow n a p.1).coef q.1 q.2 * t q.1 q.2 +
        ∑ q ∈ vars n a, (rows.map fun p => (p.2 : ℚ) * (toRow n a p.1).coef q.1 q.2).sum *
          t q.1 q.2 := by
      rw [Finset.mul_sum, ← Finset.sum_add_distrib]
      apply Finset.sum_congr rfl
      intro q _
      ring
    rw [hsplit]
    have hw : (0 : ℚ) ≤ p.2 := Nat.cast_nonneg _
    have := mul_le_mul_of_nonneg_left hp hw
    linarith

/-- `rowSum` is the coefficient of the aggregated row. -/
theorem rowSum_cast (n a : ℕ) (rows : List (CLabel × ℕ)) (j m : ℕ) :
    ((rowSum n a rows j m : ℤ) : ℚ) = (aggRow n a rows).coef j m := by
  rw [rowSum_eq, Int.cast_list_sum, List.map_map]
  simp only [aggRow]
  congr 1
  apply List.map_congr_left
  intro p _
  simp [coefZ_cast]

/-- `rhsSum` is the right side of the aggregated row. -/
theorem rhsSum_cast (n a : ℕ) (rows : List (CLabel × ℕ)) :
    ((rhsSum n a rows : ℤ) : ℚ) = (aggRow n a rows).rhs := by
  rw [rhsSum_eq, Int.cast_list_sum, List.map_map]
  simp only [aggRow]
  congr 1
  apply List.map_congr_left
  intro p _
  simp [rhsZ_cast]

/-- The layer weights: `C(v, j) = W_j`. -/
theorem binomN_cast_W (n a j : ℕ) : ((binomN (vP n a) j : ℕ) : ℚ) = W n a j := by
  rw [binomN_eq, W, binom_natCast, vP_eq]


/-! ### The generic certificate -/

/-- The target of a certificate as an affine function of the array: `−Δ_k` (`pos`) or
`Δ_{k+1}` (`neg`, `cond`). -/
theorem target_eq (n a k : ℕ) (kind : Kind) (t : ℕ → ℕ → ℚ) :
    ((tgt0Z kind a k : ℤ) : ℚ) + ∑ p ∈ vars n a, ((tgtZ kind k p.1 p.2 : ℤ) : ℚ) * t p.1 p.2 =
      if kind = .pos then -delta n a t k else delta n a t (k + 1) := by
  cases kind <;>
    simp only [tgt0Z, tgtZ, delta, Int.cast_neg, BZ_cast, neg_mul, Finset.sum_neg_distrib,
      if_true, reduceCtorEq, if_false]
  ring

/-- **Soundness of the generic certificate check**: if `genericOK n a k kind σ rows = true`, no
feasible array recovers at `k`.  The proof is Zhang's certificate principle (40) in the form
`Cert.certificate_bound`, applied to the single aggregated row `Σ w_ρ · row ρ` (scale `1`,
multiplier `1`), the target `σ · (−B(k))` or `σ · B(k + 1)`, the constant `η` computed by the
checker and the layer maxima `M_j = layerMax …` computed by the checker. -/
theorem genericOK_sound {n a k : ℕ} {kind : Kind} {σ : ℕ} {rows : List (CLabel × ℕ)}
    (h : genericOK n a k kind σ rows = true) : NoRecovery n a k := by
  intro t hF hk
  simp only [genericOK, Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true] at h
  obtain ⟨⟨⟨hv, hσ⟩, hrowsOK⟩, hsign⟩ := h
  set η := autoEta n a k kind σ rows with hη
  have hrows : ∀ p ∈ rows, (toRow n a p.1).Holds n a t :=
    fun p hp => toRow_holds hF hk (hrowsOK p hp)
  have hM : ∀ j, 0 ≤ layerMax n a k kind σ rows (if j = 1 then η else 0) j ∧
      ∀ m < a + 1 - j, preZ n a k kind σ rows j m - (if j = 1 then η else 0) ≤
        layerMax n a k kind σ rows (if j = 1 then η else 0) j := by
    intro j
    have hf := foldl_max_ge
      (fun m => preZ n a k kind σ (layerRows rows j) j m - (if j = 1 then η else 0))
      (List.range (a + 1 - j)) 0
    have hdef : layerMax n a k kind σ rows (if j = 1 then η else 0) j =
        (List.range (a + 1 - j)).foldl (fun acc m =>
          max acc (preZ n a k kind σ (layerRows rows j) j m - (if j = 1 then η else 0))) 0 := rfl
    rw [hdef]
    refine ⟨hf.1, fun m hm => ?_⟩
    have h2 := hf.2 m (List.mem_range.mpr hm)
    have h3 : preZ n a k kind σ (layerRows rows j) j m = preZ n a k kind σ rows j m := by
      simp only [preZ, rowSum_layerRows]
    rw [← h3]
    exact h2
  have key := certificate_bound hF.toBasic hv ({()} : Finset Unit) (fun _ => aggRow n a rows)
    (fun _ _ => aggRow_holds hrows) (fun _ => 1) (fun _ => 1) (fun _ _ => one_pos)
    (fun _ _ => zero_le_one) (η : ℚ) ((σ : ℚ) * ((tgt0Z kind a k : ℤ) : ℚ))
    (fun j m => (σ : ℚ) * ((tgtZ kind k j m : ℤ) : ℚ))
    (fun j => ((layerMax n a k kind σ rows (if j = 1 then η else 0) j : ℤ) : ℚ))
    (fun j _ => Int.cast_nonneg (hM j).1) (by
      intro p hp
      rw [mem_vars, Finset.mem_Icc, Finset.mem_range] at hp
      have h1 := (hM p.1).2 p.2 hp.2
      have hcast : (((preZ n a k kind σ rows p.1 p.2 - (if p.1 = 1 then η else 0) : ℤ)) : ℚ) =
          W n a p.1 * ((σ : ℚ) * ((tgtZ kind k p.1 p.2 : ℤ) : ℚ)) -
            ∑ r ∈ ({()} : Finset Unit), (1 : ℚ) * (W n a p.1 * (aggRow n a rows).coef p.1 p.2 / 1) -
            (if p.1 = 1 then (η : ℚ) else 0) := by
        rw [Finset.sum_singleton]
        simp only [preZ, Int.cast_sub, Int.cast_mul, Int.cast_natCast, binomN_cast_W,
          rowSum_cast]
        split_ifs <;> push_cast <;> ring
      rw [← hcast]
      exact Int.cast_le.mpr h1)
  have hbound : (σ : ℚ) * ((tgt0Z kind a k : ℤ) : ℚ) +
      ∑ r ∈ ({()} : Finset Unit), (1 : ℚ) * ((aggRow n a rows).rhs / 1) + (η : ℚ) +
      ∑ j ∈ Icc 1 (v n a), ((layerMax n a k kind σ rows (if j = 1 then η else 0) j : ℤ) : ℚ) =
      ((boundWith n a k kind σ rows η : ℤ) : ℚ) := by
    rw [sum_Icc_eq_foldl, Finset.sum_singleton, ← rhsSum_cast, boundWith, ← vP_eq]
    push_cast
    ring
  have hL : (σ : ℚ) * ((tgt0Z kind a k : ℤ) : ℚ) +
      ∑ p ∈ vars n a, (σ : ℚ) * ((tgtZ kind k p.1 p.2 : ℤ) : ℚ) * t p.1 p.2 =
      (σ : ℚ) * (((tgt0Z kind a k : ℤ) : ℚ) +
        ∑ p ∈ vars n a, ((tgtZ kind k p.1 p.2 : ℤ) : ℚ) * t p.1 p.2) := by
    rw [mul_add, Finset.mul_sum]
    congr 1
    apply Finset.sum_congr rfl
    intro p _
    ring
  rw [hL, hbound, target_eq] at key
  have hσ' : (0 : ℚ) < σ := by exact_mod_cast hσ
  cases kind with
  | pos =>
    simp only [signOK, decide_eq_true_eq] at hsign
    have hb : ((boundWith n a k Kind.pos σ rows η : ℤ) : ℚ) < 0 := by exact_mod_cast hsign
    simp only [if_true] at key
    exfalso
    nlinarith
  | neg =>
    simp only [signOK, decide_eq_true_eq] at hsign
    have hb : ((boundWith n a k Kind.neg σ rows η : ℤ) : ℚ) ≤ 0 := by exact_mod_cast hsign
    simp only [reduceCtorEq, if_false] at key
    nlinarith
  | cond =>
    simp only [signOK, decide_eq_true_eq] at hsign
    have hb : ((boundWith n a k Kind.cond σ rows η : ℤ) : ℚ) ≤ 0 := by exact_mod_cast hsign
    simp only [reduceCtorEq, if_false] at key
    nlinarith


/-! ### Triples, orders, ranges -/

/-- A triple that passes `tripleOK` (with any stored data) has no recovery. -/
theorem tripleOK_sound {n a k : ℕ} {c : Option CertData} (h : tripleOK n a k c = true) :
    NoRecovery n a k := by
  cases c with
  | none =>
    simp only [tripleOK, directOK, Bool.or_eq_true] at h
    rcases h with (h | h) | h <;> exact genericOK_sound h
  | some d =>
    cases d with
    | sep p q => exact genericOK_sound h
    | lin kind D rows => exact genericOK_sound h

/-- **The check of the order `n`** (with any data string) gives no recovery on every triple of
`P60` with first coordinate `n`. -/
theorem checkN_sound {n : ℕ} {s : String} (h : checkN n s = true) :
    ∀ a k, InP60 n a k → NoRecovery n a k := by
  intro a k hP
  unfold InP60 at hP
  unfold checkN at h
  simp only at h
  split at h
  · exact absurd h Bool.false_ne_true
  · rename_i es _
    rw [List.all_eq_true] at h
    have ha := h a (by rw [List.mem_range'_1]; omega)
    rw [List.all_eq_true] at ha
    exact tripleOK_sound (ha k (by rw [List.mem_range'_1]; omega))

/-- **The check of the orders `lo ≤ n ≤ hi`** gives no recovery on every triple of `P60` with
`lo ≤ n ≤ hi`. -/
theorem checkRange_sound {lo hi : ℕ} (h : checkRange lo hi = true) :
    ∀ n a k, lo ≤ n → n ≤ hi → InP60 n a k → NoRecovery n a k := by
  intro n a k hlo hhi hP
  unfold checkRange at h
  rw [List.all_eq_true] at h
  exact checkN_sound (h n (by rw [List.mem_range'_1]; omega)) a k hP

end ZhangCertX

end Erdos993Lean
