import Mathlib

/-!
# Rooted pairs: the abstract rooted-tree recursion

For a rooted tree `(T, r)` let `Z = I(T)` and `X = I(T - r)`.  If the branches of `T` at `r` are
rooted trees `(T_i, r_i)` with pairs `(Z_i, X_i)`, then
`X = ∏ Z_i` and `Z = ∏ Z_i + x ∏ X_i`.

`RootedPair k Z X` is the set of pairs generated by this recursion from nothing (a single vertex is
the case of an empty list of branches: `Z = 1 + x`, `X = 1`); `k` is the number of vertices.

This file is the interface between the graph side of the floor computation
(`Floor/TreeDecomp.lean`: every rooted tree inside a forest gives a `RootedPair`) and the
computational side (`Floor/Enumeration.lean`: every `RootedPair` of small order appears in a finite
table, and every tree assembled from table entries passes the log-concavity check).
-/

namespace Erdos993Lean

open Polynomial

/-- The rooted pairs `(Z, X) = (I(T), I(T - r))` of rooted trees with `k` vertices, generated by
the rooted recursion.  A branch is recorded as `(size, Z, X)`. -/
inductive RootedPair : ℕ → ℤ[X] → ℤ[X] → Prop
  | node (branches : List (ℕ × ℤ[X] × ℤ[X]))
      (h : ∀ b ∈ branches, RootedPair b.1 b.2.1 b.2.2) :
      RootedPair ((branches.map (·.1)).sum + 1)
        ((branches.map (·.2.1)).prod + X * (branches.map (·.2.2)).prod)
        ((branches.map (·.2.1)).prod)

end Erdos993Lean
