import Erdos993Lean.ZhangKernel.Core

/-!
# Kernel-checked finite part: check items of the orders 2 to 20 (generated)

For every `(n, a)` of these orders, `items_n_a` lists the check items of `k = 1, …,
⌊(2a+1)/3⌋ − 1` (223 weighted rows in total).  Generated by the lane-K scratch script
`gen_all.lean` (campaign `ProofRuns/2026-09-28_analytic_large_n`, `LEAN/lanes/K/scratch/`),
which evaluates the package's own functions: the stored certificates of the order `n` are
parsed from `ZhangCertX.dataFor n` by `ZhangCertX.parseEntries (ZhangCertX.tokens ·)` and
looked up by `ZhangCertX.lookup`; a separator `p/q` becomes the generic certificate
`gen .cond q [(.assumption k, p)]` and a linear certificate the generic certificate
`ZhangCertX.linearToGeneric` (the author's normalization (39)), exactly as
`ZhangCertX.storedOK` checks them; a triple without a stored certificate gets `direct h`,
`h` the first direct criterion of `ZhangCertX.directOK` that passes (`0` the path row, `1` the
lower layer rule, `2` the upper layer rule).  The generator's output has SHA-256
`305c0beb46e516e41a563ebc8dd8a17d3ba1763c67cff82bd29ab60c0b96523a`.

The items carry no trust: the soundness of `checkAV` (`ZhangKernel/Sound.lean`) holds for
arbitrary items.
-/

namespace Erdos993Lean

namespace ZhangKernel

open ZhangCertX

set_option maxRecDepth 20000

/-- The check items of `(n, a) = (2, 1)`. -/
def items_2_1 : List TItem :=
  []

/-- The check items of `(n, a) = (3, 2)`. -/
def items_3_2 : List TItem :=
  []

/-- The check items of `(n, a) = (4, 2)`. -/
def items_4_2 : List TItem :=
  []

/-- The check items of `(n, a) = (4, 3)`. -/
def items_4_3 : List TItem :=
  [.direct 1]

/-- The check items of `(n, a) = (5, 3)`. -/
def items_5_3 : List TItem :=
  [.direct 1]

/-- The check items of `(n, a) = (5, 4)`. -/
def items_5_4 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (6, 3)`. -/
def items_6_3 : List TItem :=
  [.direct 1]

/-- The check items of `(n, a) = (6, 4)`. -/
def items_6_4 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (6, 5)`. -/
def items_6_5 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (7, 4)`. -/
def items_7_4 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (7, 5)`. -/
def items_7_5 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (7, 6)`. -/
def items_7_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 1]

/-- The check items of `(n, a) = (8, 4)`. -/
def items_8_4 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (8, 5)`. -/
def items_8_5 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (8, 6)`. -/
def items_8_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 1]

/-- The check items of `(n, a) = (8, 7)`. -/
def items_8_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (9, 5)`. -/
def items_9_5 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (9, 6)`. -/
def items_9_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (9, 7)`. -/
def items_9_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 2]

/-- The check items of `(n, a) = (9, 8)`. -/
def items_9_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 1,
  .direct 1]

/-- The check items of `(n, a) = (10, 5)`. -/
def items_10_5 : List TItem :=
  [.direct 1,
  .direct 0]

/-- The check items of `(n, a) = (10, 6)`. -/
def items_10_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (10, 7)`. -/
def items_10_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 2]

/-- The check items of `(n, a) = (10, 8)`. -/
def items_10_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1]

/-- The check items of `(n, a) = (10, 9)`. -/
def items_10_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (11, 6)`. -/
def items_11_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (11, 7)`. -/
def items_11_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 2]

/-- The check items of `(n, a) = (11, 8)`. -/
def items_11_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1]

/-- The check items of `(n, a) = (11, 9)`. -/
def items_11_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (11, 10)`. -/
def items_11_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (12, 6)`. -/
def items_12_6 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (12, 7)`. -/
def items_12_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .gen .neg 8160000 [(.count 3, 7480680), (.count 4, 16320000), (.count 5, 8160000), (.path 2, 2719800), (.priv 2 2, 1359915), (.priv 2 3, 680000), (.priv 3 0, 680000)]]

/-- The check items of `(n, a) = (12, 8)`. -/
def items_12_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .gen .cond 1 [(.assumption 4, 1)]]

/-- The check items of `(n, a) = (12, 9)`. -/
def items_12_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (12, 10)`. -/
def items_12_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (12, 11)`. -/
def items_12_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (13, 7)`. -/
def items_13_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .gen .pos 280000 [(.count 2, 560000), (.count 3, 280035), (.path 4, 186672)]]

/-- The check items of `(n, a) = (13, 8)`. -/
def items_13_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .gen .pos 350000 [(.count 2, 630000), (.count 3, 349965), (.path 4, 210006)]]

/-- The check items of `(n, a) = (13, 9)`. -/
def items_13_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (13, 10)`. -/
def items_13_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (13, 11)`. -/
def items_13_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (13, 12)`. -/
def items_13_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (14, 7)`. -/
def items_14_7 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (14, 8)`. -/
def items_14_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (14, 9)`. -/
def items_14_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 2 [(.assumption 5, 1)]]

/-- The check items of `(n, a) = (14, 10)`. -/
def items_14_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (14, 11)`. -/
def items_14_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (14, 12)`. -/
def items_14_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (14, 13)`. -/
def items_14_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (15, 8)`. -/
def items_15_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (15, 9)`. -/
def items_15_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 103320000 [(.count 2, 272902560), (.count 3, 156426480), (.count 4, 124328400), (.path 4, 63422800), (.priv 3 3, 4094055), (.priv 3 4, 14769020), (.priv 4 1, 16028376), (.priv 6 0, 25830000), (.hall 4 1, 16014600), (.assumption 5, 92978160)]]

/-- The check items of `(n, a) = (15, 10)`. -/
def items_15_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 2 [(.assumption 5, 3)],
  .direct 2]

/-- The check items of `(n, a) = (15, 11)`. -/
def items_15_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (15, 12)`. -/
def items_15_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (15, 13)`. -/
def items_15_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (15, 14)`. -/
def items_15_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (16, 8)`. -/
def items_16_8 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0]

/-- The check items of `(n, a) = (16, 9)`. -/
def items_16_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 70000 [(.count 2, 280035), (.count 3, 98028), (.count 4, 69993), (.path 5, 27999)]]

/-- The check items of `(n, a) = (16, 10)`. -/
def items_16_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 20000 [(.count 2, 80024), (.count 3, 28014), (.count 4, 19992), (.path 5, 8000)],
  .gen .cond 2 [(.assumption 6, 1)]]

/-- The check items of `(n, a) = (16, 11)`. -/
def items_16_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 5 [(.assumption 6, 4)]]

/-- The check items of `(n, a) = (16, 12)`. -/
def items_16_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (16, 13)`. -/
def items_16_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (16, 14)`. -/
def items_16_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (16, 15)`. -/
def items_16_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (17, 9)`. -/
def items_17_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 129000000 [(.count 2, 645051600), (.count 3, 193538700), (.count 4, 129010320), (.path 5, 64500800), (.priv 6 0, 10748925), (.hall 4 2, 2148624)]]

/-- The check items of `(n, a) = (17, 10)`. -/
def items_17_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 100000 [(.count 2, 500080), (.count 3, 150024), (.count 4, 99960), (.path 5, 50000)],
  .gen .neg 201000000 [(.count 2, 129725400), (.count 3, 85264200), (.count 6, 602758800), (.count 7, 200919600), (.path 3, 85236480), (.priv 2 5, 62963250), (.priv 2 6, 153316100), (.priv 2 7, 146187300), (.priv 3 3, 66410400), (.priv 3 4, 80395980), (.priv 3 5, 42641480), (.priv 4 1, 49807800), (.priv 4 2, 38520846), (.priv 5 0, 38654980)]]

/-- The check items of `(n, a) = (17, 11)`. -/
def items_17_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 15 [(.assumption 6, 14)]]

/-- The check items of `(n, a) = (17, 12)`. -/
def items_17_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 5 [(.assumption 6, 9)],
  .direct 2]

/-- The check items of `(n, a) = (17, 13)`. -/
def items_17_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (17, 14)`. -/
def items_17_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (17, 15)`. -/
def items_17_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (17, 16)`. -/
def items_17_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (18, 9)`. -/
def items_18_9 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 26800000 [(.count 2, 150098760), (.count 3, 38592000), (.count 4, 26805360), (.path 5, 11792520), (.path 6, 3216402), (.priv 6 0, 1697445), (.hall 0 2, 21442680), (.hall 4 2, 1000712)]]

/-- The check items of `(n, a) = (18, 10)`. -/
def items_18_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 3750000 [(.count 2, 21000000), (.count 3, 5402250), (.count 4, 3750600), (.path 5, 1649928), (.path 6, 450000), (.priv 6 0, 199850), (.hall 4 2, 70000)],
  .gen .cond 45000000 [(.count 2, 175329000), (.count 3, 77805000), (.count 4, 76658400), (.count 5, 14332500), (.count 7, 44982000), (.path 5, 19344528), (.priv 3 5, 5257000), (.priv 4 3, 7445025), (.priv 4 4, 2868600), (.priv 5 0, 6233850), (.priv 6 0, 4105500), (.hall 2 7, 10087875), (.assumption 6, 32379750)]]

/-- The check items of `(n, a) = (18, 11)`. -/
def items_18_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1750000 [(.count 2, 11247600), (.count 3, 2998800), (.count 4, 1748880), (.path 5, 1000000), (.hall 3 4, 35712)],
  .gen .cond 82800000 [(.count 2, 743240400), (.count 3, 271716480), (.count 4, 139683600), (.count 5, 23377200), (.path 4, 75213040), (.priv 3 5, 7583100), (.priv 3 6, 39438560), (.priv 4 3, 26389188), (.priv 4 4, 8751960), (.priv 5 1, 20569360), (.priv 6 0, 11270000), (.priv 7 0, 16576560), (.assumption 6, 64468080)]]

/-- The check items of `(n, a) = (18, 12)`. -/
def items_18_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 2 [(.assumption 6, 3)],
  .gen .cond 29 [(.assumption 7, 14)]]

/-- The check items of `(n, a) = (18, 13)`. -/
def items_18_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 7 [(.assumption 7, 6)],
  .direct 2]

/-- The check items of `(n, a) = (18, 14)`. -/
def items_18_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (18, 15)`. -/
def items_18_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (18, 16)`. -/
def items_18_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (18, 17)`. -/
def items_18_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (19, 10)`. -/
def items_19_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 16800000 [(.count 2, 86553600), (.count 3, 36300600), (.count 4, 22352400), (.count 5, 20386800), (.count 7, 16787400), (.path 6, 8399880), (.priv 4 3, 1400175), (.priv 5 1, 1959888), (.priv 6 0, 1457820), (.hall 4 4, 168280), (.hall 3 5, 930900), (.hall 2 7, 5832225), (.assumption 6, 22350600)]]

/-- The check items of `(n, a) = (19, 11)`. -/
def items_19_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 435600000 [(.count 2, 3523350600), (.count 3, 1301246100), (.count 4, 744614640), (.count 5, 625086000), (.path 5, 248102400), (.priv 3 6, 156271500), (.priv 4 3, 25369344), (.priv 4 4, 142283295), (.priv 5 1, 59561040), (.priv 5 2, 35370720), (.priv 6 0, 68310550), (.priv 7 0, 87054660), (.hall 2 8, 78940400), (.assumption 6, 496202850)]]

/-- The check items of `(n, a) = (19, 12)`. -/
def items_19_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 40000 [(.count 2, 699840), (.count 3, 200016), (.count 4, 79920), (.count 5, 60120), (.path 5, 20001)],
  .gen .neg 966000000 [(.count 3, 1129756320), (.count 7, 3838111200), (.path 3, 1130865120), (.priv 2 5, 859997600), (.priv 2 6, 74807040), (.priv 2 8, 2065694400), (.priv 2 9, 1971123000), (.priv 3 4, 154006160), (.priv 3 5, 992723424), (.priv 3 6, 965903400), (.priv 3 7, 458759840), (.priv 4 1, 76985370), (.priv 4 2, 196368480), (.priv 4 3, 593355840), (.priv 4 4, 301948416), (.priv 5 0, 467012700), (.priv 6 0, 234986400)]]

/-- The check items of `(n, a) = (19, 13)`. -/
def items_19_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 7 [(.assumption 7, 6)],
  .direct 2]

/-- The check items of `(n, a) = (19, 14)`. -/
def items_19_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2]

/-- The check items of `(n, a) = (19, 15)`. -/
def items_19_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (19, 16)`. -/
def items_19_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (19, 17)`. -/
def items_19_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (19, 18)`. -/
def items_19_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (20, 10)`. -/
def items_20_10 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 164400000 [(.count 2, 2171789760), (.count 3, 657164340), (.count 4, 319494960), (.count 5, 313428600), (.path 6, 127815840), (.priv 5 1, 6095952), (.priv 7 0, 41102055), (.hall 5 1, 25124430), (.hall 5 2, 9891400), (.hall 4 3, 10812588), (.hall 0 4, 38781960), (.hall 3 5, 15646770), (.assumption 6, 319538800)]]

/-- The check items of `(n, a) = (20, 11)`. -/
def items_20_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 900000 [(.count 2, 12600840), (.count 3, 3601080), (.count 4, 1260000), (.count 5, 900480), (.path 6, 360000), (.priv 7 0, 67536), (.hall 5 3, 11256)]]

/-- The check items of `(n, a) = (20, 12)`. -/
def items_20_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 350000 [(.count 2, 4898880), (.count 3, 1399440), (.count 4, 490560), (.count 5, 349440), (.path 6, 140000)],
  .gen .cond 1131000000 [(.count 2, 18511529400), (.count 3, 5569609500), (.count 4, 1793675520), (.count 5, 11875500), (.count 8, 1197050400), (.path 4, 1319472000), (.priv 2 10, 1147173300), (.priv 3 7, 1099671300), (.priv 3 8, 658694400), (.priv 4 4, 225064476), (.priv 4 5, 861923790), (.priv 4 6, 71253000), (.priv 5 2, 276778320), (.priv 5 3, 347239620), (.priv 6 0, 30763200), (.priv 6 1, 258753950), (.priv 7 0, 112421400), (.assumption 7, 474058650)]]

/-- The check items of `(n, a) = (20, 13)`. -/
def items_20_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 44400000 [(.count 2, 1253145600), (.count 3, 322610400), (.count 4, 99207360), (.count 5, 13986000), (.path 4, 69344800), (.priv 2 11, 22066800), (.priv 3 7, 27241620), (.priv 3 8, 57539440), (.priv 4 4, 1017870), (.priv 4 5, 50769180), (.priv 4 6, 5675985), (.priv 5 2, 5851920), (.priv 5 3, 24190600), (.priv 6 0, 757575), (.priv 6 1, 11921400), (.priv 7 0, 4528800), (.assumption 7, 29898960)],
  .direct 2]

/-- The check items of `(n, a) = (20, 14)`. -/
def items_20_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 7 [(.assumption 7, 12)],
  .direct 2]

/-- The check items of `(n, a) = (20, 15)`. -/
def items_20_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 24 [(.assumption 8, 19)],
  .direct 2]

/-- The check items of `(n, a) = (20, 16)`. -/
def items_20_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (20, 17)`. -/
def items_20_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (20, 18)`. -/
def items_20_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (20, 19)`. -/
def items_20_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

end ZhangKernel

end Erdos993Lean
