import Erdos993Lean.ZhangKernel.Core

/-!
# Kernel-checked finite part: check items of the orders 21 to 30 (generated)

For every `(n, a)` of these orders, `items_n_a` lists the check items of `k = 1, …,
⌊(2a+1)/3⌋ − 1` (2287 weighted rows in total).  Generated by the lane-K scratch script
`gen_all.lean` (campaign `ProofRuns/2026-09-28_analytic_large_n`, `LEAN/lanes/K/scratch/`),
which evaluates the package's own functions: the stored certificates of the order `n` are
parsed from `ZhangCertX.dataFor n` by `ZhangCertX.parseEntries (ZhangCertX.tokens ·)` and
looked up by `ZhangCertX.lookup`; a separator `p/q` becomes the generic certificate
`gen .cond q [(.assumption k, p)]` and a linear certificate the generic certificate
`ZhangCertX.linearToGeneric` (the author's normalization (39)), exactly as
`ZhangCertX.storedOK` checks them; a triple without a stored certificate gets `direct h`,
`h` the first direct criterion of `ZhangCertX.directOK` that passes (`0` the path row, `1` the
lower layer rule, `2` the upper layer rule).  The generator's output has SHA-256
`305c0beb46e516e41a563ebc8dd8a17d3ba1763c67cff82bd29ab60c0b96523a`.

The items carry no trust: the soundness of `checkAV` (`ZhangKernel/Sound.lean`) holds for
arbitrary items.
-/

namespace Erdos993Lean

namespace ZhangKernel

open ZhangCertX

set_option maxRecDepth 20000

/-- The check items of `(n, a) = (21, 11)`. -/
def items_21_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 242550000 [(.count 2, 2910341280), (.count 3, 692722800), (.count 4, 277089120), (.count 5, 242550000), (.path 6, 34646400), (.path 7, 69301386), (.priv 6 0, 5616380), (.priv 7 0, 13854456), (.hall 5 2, 4026330), (.hall 4 3, 3711708)]]

/-- The check items of `(n, a) = (21, 12)`. -/
def items_21_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 150000 [(.count 2, 2400720), (.count 3, 642960), (.count 4, 214080), (.count 5, 149760), (.path 6, 64288)],
  .gen .cond 8094000000 [(.count 2, 128064077400), (.count 3, 42017572800), (.count 4, 16929410400), (.count 5, 10153113600), (.count 6, 3620446200), (.count 8, 8090762400), (.path 5, 4729460400), (.priv 3 7, 2000027400), (.priv 4 5, 3137436750), (.priv 4 6, 3547735100), (.priv 5 3, 2919020160), (.priv 5 4, 861768180), (.priv 6 1, 1793697850), (.priv 7 0, 748829900), (.hall 2 9, 8606350200), (.assumption 7, 5418528300)]]

/-- The check items of `(n, a) = (21, 13)`. -/
def items_21_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .cond 2 [(.assumption 6, 5)],
  .gen .cond 5881200000 [(.count 2, 127580871600), (.count 3, 41652128700), (.count 4, 16277985360), (.count 5, 9108508500), (.count 6, 1976083200), (.path 5, 3920666400), (.priv 2 11, 5526857700), (.priv 3 8, 7544109300), (.priv 3 9, 3000147150), (.priv 4 5, 1960027524), (.priv 4 6, 5074519905), (.priv 5 3, 2940452970), (.priv 5 4, 600235272), (.priv 6 1, 1593805200), (.priv 7 0, 701333100), (.priv 8 0, 972603450), (.assumption 7, 5194079800)],
  .gen .neg 3447853500000 [(.count 2, 98123152327200), (.count 3, 26374010562900), (.count 4, 7354685257920), (.count 5, 1388105819100), (.path 4, 3179567270880), (.path 5, 1393672896000), (.priv 2 11, 7190843259600), (.priv 3 8, 5347620778500), (.priv 3 9, 4945601060400), (.priv 4 5, 729096892524), (.priv 4 6, 4238273914875), (.priv 4 7, 2060161423320), (.priv 5 3, 877616629890), (.priv 5 4, 2829915404316), (.priv 6 1, 585149994000), (.priv 6 2, 1206059154300), (.priv 7 0, 767196658800), (.priv 8 0, 345130135350)]]

/-- The check items of `(n, a) = (21, 14)`. -/
def items_21_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 7 [(.assumption 7, 12)],
  .gen .cond 7 [(.assumption 8, 5)]]

/-- The check items of `(n, a) = (21, 15)`. -/
def items_21_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 24 [(.assumption 8, 19)],
  .direct 2]

/-- The check items of `(n, a) = (21, 16)`. -/
def items_21_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (21, 17)`. -/
def items_21_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (21, 18)`. -/
def items_21_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (21, 19)`. -/
def items_21_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (21, 20)`. -/
def items_21_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (22, 11)`. -/
def items_22_11 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 255300000 [(.count 2, 3103120440), (.count 3, 716984520), (.count 4, 286650840), (.count 5, 255300000), (.path 6, 31482000), (.path 7, 80419500), (.priv 7 0, 16083900), (.hall 5 1, 11888470), (.hall 5 2, 3731635), (.hall 0 3, 119110215), (.hall 4 3, 4437114), (.hall 3 6, 8437665), (.hall 0 8, 5242160), (.hall 1 8, 15249920)]]

/-- The check items of `(n, a) = (22, 12)`. -/
def items_22_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 3006150000 [(.count 2, 36285432960), (.count 3, 8643282480), (.count 4, 3446593920), (.count 5, 3009585600), (.path 6, 438177600), (.path 7, 851914280), (.priv 3 9, 19239360), (.priv 4 5, 304050600), (.priv 5 2, 213007200), (.priv 5 3, 274848), (.priv 6 0, 160786080), (.priv 7 0, 141890280), (.hall 3 7, 4008200)],
  .gen .cond 2454000000 [(.count 2, 33014741760), (.count 3, 11788917840), (.count 4, 5206995360), (.count 5, 5198062800), (.count 6, 737966880), (.count 8, 2462638080), (.path 6, 981590400), (.priv 4 5, 350688870), (.priv 5 3, 385611744), (.priv 5 4, 604837380), (.priv 6 0, 371633760), (.priv 6 2, 70361088), (.priv 7 0, 207166680), (.hall 3 7, 378875105), (.hall 2 9, 2901295488), (.assumption 7, 2358490320)]]

/-- The check items of `(n, a) = (22, 13)`. -/
def items_22_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 660000 [(.count 2, 13860000), (.count 3, 3301650), (.count 4, 990000), (.count 5, 660000), (.path 6, 330015)],
  .gen .cond 22000000 [(.count 2, 514206000), (.count 3, 154123200), (.count 4, 64125600), (.count 5, 37699200), (.count 6, 29521800), (.path 6, 10763340), (.priv 3 8, 11704000), (.priv 3 9, 19149900), (.priv 4 5, 397320), (.priv 4 6, 15407700), (.priv 4 7, 7623000), (.priv 5 3, 2500960), (.priv 5 4, 9790704), (.priv 6 1, 4059000), (.priv 6 2, 1278200), (.priv 7 0, 2956800), (.priv 8 0, 3665200), (.assumption 7, 26906880)],
  .gen .neg 4724114500000 [(.count 2, 225861803890800), (.count 3, 40461635768400), (.count 4, 4133465212800), (.count 9, 4489798420800), (.path 3, 23913171097200), (.path 4, 4133995034400), (.priv 2 11, 16649669143800), (.priv 3 7, 1897474332600), (.priv 3 8, 8857849662200), (.priv 3 9, 8658896954400), (.priv 4 4, 97991632200), (.priv 4 5, 2994980613240), (.priv 4 6, 5412924137775), (.priv 4 7, 3894425019100), (.priv 5 2, 59049503040), (.priv 5 3, 2142750357440), (.priv 5 4, 3571171410576), (.priv 5 5, 138079118100), (.priv 6 1, 1174626967800), (.priv 6 2, 1488433504250), (.priv 7 0, 1117359130800), (.priv 8 0, 462490809550), (.hall 2 10, 1388889663000)]]

/-- The check items of `(n, a) = (22, 14)`. -/
def items_22_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 5750000 [(.count 2, 496765500), (.count 3, 111573000), (.count 4, 25274700), (.count 5, 5787375), (.count 6, 5692500), (.path 4, 13800864)],
  .gen .cond 234255000000 [(.count 2, 13998235482000), (.count 3, 2914366455000), (.count 4, 598643337600), (.count 5, 35559909000), (.path 3, 239324085000), (.path 4, 514334221632), (.priv 2 12, 751396338000), (.priv 3 8, 170197970250), (.priv 3 9, 658115997000), (.priv 3 10, 339880579500), (.priv 4 6, 302351991480), (.priv 4 7, 414350244000), (.priv 5 3, 16300132200), (.priv 5 4, 268296936600), (.priv 5 5, 74211984000), (.priv 6 2, 156890613000), (.priv 7 0, 58557893625), (.priv 8 0, 21645162000), (.assumption 8, 84530916750)]]

/-- The check items of `(n, a) = (22, 15)`. -/
def items_22_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 11 [(.assumption 8, 13)],
  .direct 2]

/-- The check items of `(n, a) = (22, 16)`. -/
def items_22_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 1 [(.assumption 8, 2)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (22, 17)`. -/
def items_22_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 288 [(.assumption 9, 215)],
  .direct 2]

/-- The check items of `(n, a) = (22, 18)`. -/
def items_22_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (22, 19)`. -/
def items_22_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (22, 20)`. -/
def items_22_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (22, 21)`. -/
def items_22_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (23, 12)`. -/
def items_23_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 7350000 [(.count 2, 103088160), (.count 3, 23355360), (.count 4, 8749440), (.count 5, 7345800), (.path 6, 1405140), (.path 7, 1863400), (.priv 6 0, 393300), (.priv 7 0, 310380), (.hall 4 3, 80199), (.hall 3 6, 92680)],
  .gen .cond 9000000 [(.count 2, 222158160), (.count 3, 64527120), (.count 4, 25401600), (.count 5, 14817600), (.count 6, 14023800), (.count 8, 8996400), (.path 7, 4763080), (.priv 3 9, 2457840), (.priv 5 3, 530208), (.priv 6 1, 794500), (.priv 7 0, 720720), (.hall 5 5, 513300), (.hall 3 7, 1237250), (.hall 4 7, 8564220), (.assumption 7, 14815080)]]

/-- The check items of `(n, a) = (23, 13)`. -/
def items_23_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 229320000 [(.count 2, 4815720000), (.count 3, 982062900), (.count 4, 311547600), (.count 5, 229320000), (.path 6, 81903500), (.path 7, 32760000), (.priv 6 2, 4995900), (.priv 7 0, 4668300), (.hall 4 3, 128700), (.hall 5 5, 887250)],
  .gen .cond 13200000 [(.count 2, 554436960), (.count 3, 151448220), (.count 4, 50893920), (.count 5, 27627600), (.count 6, 25890480), (.path 7, 8800176), (.priv 4 6, 4029795), (.priv 4 7, 7253400), (.priv 5 4, 5484864), (.priv 5 5, 1700160), (.priv 6 1, 880440), (.priv 6 2, 2534840), (.priv 7 0, 2017620), (.priv 8 0, 2199120), (.hall 3 9, 911988), (.hall 2 10, 12489120), (.assumption 7, 27640998)],
  .gen .neg 568400000 [(.count 2, 17811837120), (.count 3, 3030225660), (.count 6, 855328320), (.count 7, 5115088440), (.count 8, 2273372640), (.count 9, 573970320), (.path 3, 3031551600), (.priv 2 10, 2083924920), (.priv 3 7, 615705090), (.priv 3 8, 1255169300), (.priv 4 4, 81191880), (.priv 4 5, 419544972), (.priv 4 6, 585325125), (.priv 4 7, 467188260), (.priv 5 2, 40615080), (.priv 5 3, 234598980), (.priv 5 4, 350062944), (.priv 6 0, 24350865), (.priv 6 1, 101939640), (.priv 6 2, 73599680), (.hall 2 10, 1825928160), (.hall 1 11, 2084862780)]]

/-- The check items of `(n, a) = (23, 14)`. -/
def items_23_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 90000 [(.count 2, 4535685), (.count 3, 1259280), (.count 4, 396000), (.count 5, 162360), (.count 6, 126225), (.path 6, 36001)],
  .gen .cond 27751758000000 [(.count 2, 1396007783377200), (.count 3, 355616577363600), (.count 4, 92779677345600), (.count 5, 25409509624800), (.count 9, 29372460667200), (.path 4, 33093685522800), (.path 5, 11171055319200), (.priv 2 12, 112798407978900), (.priv 3 9, 66515413574400), (.priv 3 10, 65213856124200), (.priv 4 6, 13066082701560), (.priv 4 7, 44226242239725), (.priv 4 8, 30955698461100), (.priv 5 4, 13940263078560), (.priv 5 5, 28258172079984), (.priv 5 6, 798418077660), (.priv 6 2, 10344467794500), (.priv 6 3, 8829221807700), (.priv 7 0, 2149026760125), (.priv 7 1, 5378290700400), (.priv 8 0, 2535123093300), (.hall 2 11, 8532971791050), (.assumption 8, 14252377850200)]]

/-- The check items of `(n, a) = (23, 15)`. -/
def items_23_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 730800000 [(.count 2, 74399094000), (.count 3, 15591252600), (.count 4, 3221951040), (.count 5, 494386200), (.path 4, 2459068920), (.priv 2 13, 3159248400), (.priv 3 9, 1426887000), (.priv 3 10, 3081540000), (.priv 3 11, 834025500), (.priv 4 6, 324767520), (.priv 4 7, 1800530424), (.priv 4 8, 1108148580), (.priv 5 4, 542274480), (.priv 5 5, 968273460), (.priv 6 2, 588339675), (.priv 7 0, 204989400), (.priv 8 0, 63305550), (.assumption 8, 498730400)],
  .gen .cond 13 [(.assumption 9, 6)]]

/-- The check items of `(n, a) = (23, 16)`. -/
def items_23_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 2 [(.assumption 8, 3)],
  .gen .cond 24 [(.assumption 9, 19)],
  .direct 2]

/-- The check items of `(n, a) = (23, 17)`. -/
def items_23_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 6 [(.assumption 9, 5)],
  .direct 2]

/-- The check items of `(n, a) = (23, 18)`. -/
def items_23_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (23, 19)`. -/
def items_23_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (23, 20)`. -/
def items_23_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (23, 21)`. -/
def items_23_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (23, 22)`. -/
def items_23_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 12)`. -/
def items_24_12 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1200000 [(.count 2, 16405200), (.count 3, 9986760), (.count 4, 2876160), (.count 5, 1199100), (.count 6, 1200600), (.path 8, 475536), (.priv 8 0, 95088), (.hall 1 1, 100800), (.hall 6 1, 67320), (.hall 6 2, 17130), (.hall 0 3, 2041200), (.hall 1 3, 129465), (.hall 5 3, 18735), (.hall 4 5, 20200), (.hall 5 6, 122100), (.hall 3 8, 52080)]]

/-- The check items of `(n, a) = (24, 13)`. -/
def items_24_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1470000 [(.count 2, 41150592), (.count 3, 10287648), (.count 4, 3429216), (.count 5, 1471680), (.count 6, 1471680), (.path 8, 490000), (.priv 7 0, 46368), (.priv 8 0, 81732), (.hall 5 3, 16272), (.hall 6 3, 12816), (.hall 4 6, 48608)],
  .gen .cond 8895600000 [(.count 2, 232730245440), (.count 3, 71979636960), (.count 4, 27555010560), (.count 5, 12147577200), (.count 6, 8485131600), (.count 7, 5029572240), (.count 9, 8924065920), (.path 6, 3558162300), (.priv 4 6, 189587475), (.priv 5 4, 367922016), (.priv 5 5, 3525453360), (.priv 6 2, 111830400), (.priv 6 3, 2505466920), (.priv 6 4, 2078181600), (.priv 7 1, 1881546480), (.priv 8 0, 745303020), (.hall 3 8, 3193876224), (.hall 4 8, 12968598720), (.hall 2 10, 21157295040), (.assumption 8, 5033765880)]]

/-- The check items of `(n, a) = (24, 14)`. -/
def items_24_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 20268360000 [(.count 2, 608212946880), (.count 3, 130203944640), (.count 4, 34780505760), (.count 5, 20278011600), (.path 6, 11581416000), (.priv 7 0, 414053640), (.hall 6 2, 10237590), (.hall 7 3, 212335200), (.hall 5 6, 310076800)],
  .gen .pos 980000 [(.count 2, 51442160), (.count 3, 12855150), (.count 4, 3677520), (.count 5, 1347500), (.count 6, 979440), (.path 7, 367500), (.hall 4 6, 39380)],
  .gen .cond 28441963000000 [(.count 2, 1553313439782720), (.count 3, 431225097381540), (.count 4, 131592999051360), (.count 5, 48977060286000), (.count 6, 28526151210480), (.count 7, 14048054364960), (.count 9, 27092676275280), (.path 5, 13040460140400), (.path 6, 7423129560000), (.priv 3 9, 12682271301700), (.priv 4 7, 23383559880450), (.priv 4 8, 34785658427520), (.priv 5 4, 55746247480), (.priv 5 5, 19184672882760), (.priv 5 6, 21699226831590), (.priv 6 3, 13773305002380), (.priv 6 4, 5084057770176), (.priv 7 1, 7192972442700), (.priv 8 0, 2472744263220), (.hall 3 10, 26727791746320), (.hall 2 11, 104022497797680), (.assumption 8, 21129420544848)]]

/-- The check items of `(n, a) = (24, 15)`. -/
def items_24_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 1 [(.assumption 7, 3)],
  .gen .cond 19446000000 [(.count 2, 1666541646000), (.count 3, 435469834800), (.count 4, 120899671200), (.count 5, 39273141600), (.count 6, 13091047200), (.count 7, 4492026000), (.path 5, 22687156800), (.priv 2 13, 75016834200), (.priv 3 10, 69990043200), (.priv 3 11, 62246646000), (.priv 4 7, 18905012280), (.priv 4 8, 46428297300), (.priv 4 9, 18673993800), (.priv 5 4, 520708320), (.priv 5 5, 21946755600), (.priv 5 6, 17885964096), (.priv 6 2, 1123006500), (.priv 6 3, 15437901600), (.priv 7 1, 6048192150), (.priv 8 0, 2077562025), (.priv 9 0, 2566872000), (.assumption 8, 16522618000)],
  .gen .neg 18228000000 [(.count 2, 2633712681600), (.count 3, 467513046000), (.count 4, 69261192000), (.path 3, 70365335040), (.path 4, 69232756320), (.priv 2 13, 188066478600), (.priv 3 9, 25917091200), (.priv 3 10, 99460561200), (.priv 3 11, 97915217400), (.priv 4 6, 3649245600), (.priv 4 7, 35982306360), (.priv 4 8, 59109400350), (.priv 4 9, 40141701600), (.priv 5 4, 5834537280), (.priv 5 5, 25328743440), (.priv 5 6, 34156938816), (.priv 6 2, 4377698325), (.priv 6 3, 18679775400), (.priv 6 4, 5334228900), (.priv 7 0, 4381577200), (.priv 7 1, 6716659950), (.priv 8 0, 4691887200), (.priv 9 0, 1787385600), (.hall 2 12, 10827432000)]]

/-- The check items of `(n, a) = (24, 16)`. -/
def items_24_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 5 [(.assumption 8, 9)],
  .gen .cond 24 [(.assumption 9, 19)],
  .direct 2]

/-- The check items of `(n, a) = (24, 17)`. -/
def items_24_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 139 [(.assumption 9, 149)],
  .direct 2]

/-- The check items of `(n, a) = (24, 18)`. -/
def items_24_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 4 [(.assumption 9, 9)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 19)`. -/
def items_24_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 504 [(.assumption 10, 359)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 20)`. -/
def items_24_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 21)`. -/
def items_24_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 22)`. -/
def items_24_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (24, 23)`. -/
def items_24_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 13)`. -/
def items_25_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 29400000 [(.count 2, 970552800), (.count 3, 220358880), (.count 4, 69289920), (.count 5, 29370600), (.count 6, 29408400), (.path 8, 10500000), (.priv 7 0, 385200), (.priv 8 0, 1749300), (.priv 9 0, 3062304), (.hall 6 2, 890640), (.hall 5 3, 592515), (.hall 4 5, 487480), (.hall 3 9, 22035888)],
  .gen .cond 702702000000 [(.count 2, 17684479612800), (.count 3, 5553257149440), (.count 4, 2062271090880), (.count 5, 997391795400), (.count 6, 725047923600), (.count 7, 555509354400), (.count 9, 702420919200), (.path 6, 170102961600), (.path 7, 79281105750), (.priv 8 0, 56928231360), (.hall 6 3, 36976179240), (.hall 5 4, 39761221500), (.hall 4 6, 73033120160), (.hall 3 8, 253606088736), (.hall 2 10, 1607679964800), (.assumption 8, 476027902350)]]

/-- The check items of `(n, a) = (25, 14)`. -/
def items_25_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 7840000 [(.count 2, 414081360), (.count 3, 94044720), (.count 4, 25742640), (.count 5, 9840600), (.count 6, 7854000), (.path 7, 2016056), (.path 8, 1120000), (.priv 3 11, 12332320), (.priv 7 1, 81840), (.priv 8 0, 159390), (.hall 6 3, 12045)],
  .gen .cond 262218000000 [(.count 2, 13451028212160), (.count 3, 4095131927040), (.count 4, 1398450548880), (.count 5, 585899899200), (.count 6, 475768339200), (.count 9, 259029429120), (.path 6, 130698876000), (.priv 3 9, 3768946720), (.priv 4 7, 116312693805), (.priv 4 8, 284983766760), (.priv 5 5, 110572086240), (.priv 5 6, 177366877380), (.priv 5 7, 106019981760), (.priv 6 3, 84036498700), (.priv 6 4, 87848274360), (.priv 7 0, 23402956500), (.priv 7 1, 40780143360), (.priv 8 0, 22081377780), (.hall 3 10, 492548384160), (.hall 2 11, 1112438887560), (.assumption 8, 227901355528)]]

/-- The check items of `(n, a) = (25, 15)`. -/
def items_25_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 4410000 [(.count 2, 291060000), (.count 3, 70582050), (.count 4, 18918900), (.count 5, 6294750), (.count 6, 4435200), (.path 7, 1889930), (.hall 4 6, 83190)],
  .gen .cond 2211627600000 [(.count 2, 197542577232000), (.count 3, 51650572133160), (.count 4, 17136575295840), (.count 5, 6763157200800), (.count 6, 3765959477280), (.count 7, 1021771951200), (.path 6, 1416465610560), (.priv 3 10, 2758784268240), (.priv 3 11, 6760724410440), (.priv 4 7, 173701231704), (.priv 4 8, 3698449544790), (.priv 4 9, 3795152961600), (.priv 4 10, 832014303120), (.priv 5 5, 720105946560), (.priv 5 6, 2376349623648), (.priv 5 7, 1206664018560), (.priv 6 3, 889706188800), (.priv 6 4, 913918245240), (.priv 7 1, 662327175510), (.priv 8 0, 268215137190), (.priv 9 0, 311397166080), (.hall 2 12, 1792030806720), (.assumption 8, 2360912463000)],
  .gen .neg 11054400000 [(.count 2, 505533188160), (.count 3, 75047492520), (.count 7, 47482655220), (.count 8, 154600205760), (.count 9, 55485349920), (.count 10, 21340519200), (.path 3, 75048573600), (.priv 2 10, 8714045340), (.priv 2 11, 102197375280), (.priv 2 12, 140965985160), (.priv 3 8, 32117481396), (.priv 3 9, 38694510855), (.priv 3 10, 75660044460), (.priv 3 11, 55426070700), (.priv 4 5, 6166248660), (.priv 4 6, 10907376480), (.priv 4 7, 25268190948), (.priv 4 8, 32919021135), (.priv 4 9, 24355290960), (.priv 5 2, 1027506480), (.priv 5 3, 2055718665), (.priv 5 4, 7294973400), (.priv 5 5, 13950376440), (.priv 5 6, 16571082528), (.priv 6 0, 1028071044), (.priv 6 1, 1439638200), (.priv 6 2, 4376076705), (.priv 6 3, 8499914280), (.priv 7 0, 4595550960), (.hall 2 12, 20975724000), (.hall 1 13, 115391235960)]]

/-- The check items of `(n, a) = (25, 16)`. -/
def items_25_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 4074150000 [(.count 2, 1377895999480), (.count 3, 209737242000), (.count 4, 29518574800), (.count 5, 8078767840), (.count 6, 3961703460), (.count 7, 3806342540), (.path 3, 79449598800), (.path 4, 9166096368)],
  .gen .cond 15054102000000 [(.count 2, 2801472035947200), (.count 3, 542787690891600), (.count 4, 107901781495200), (.count 5, 16294560004800), (.path 4, 48668005552320), (.path 5, 9307969070400), (.priv 2 14, 201347108839800), (.priv 3 10, 22653412689600), (.priv 3 11, 111611112228000), (.priv 3 12, 107653388812200), (.priv 4 8, 41123892597480), (.priv 4 9, 68332827093300), (.priv 4 10, 41481578061000), (.priv 5 5, 3258912000960), (.priv 5 6, 31502816009280), (.priv 5 7, 36738271386432), (.priv 6 3, 2744739147150), (.priv 6 4, 24094090251000), (.priv 6 5, 3808687806000), (.priv 7 1, 441586992000), (.priv 7 2, 11674456101000), (.priv 8 0, 4057080489000), (.priv 9 0, 1390999024800), (.hall 2 13, 9190529271000), (.assumption 9, 6924217848800)],
  .gen .cond 13 [(.assumption 10, 6)]]

/-- The check items of `(n, a) = (25, 17)`. -/
def items_25_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 139 [(.assumption 9, 149)],
  .gen .cond 43 [(.assumption 10, 19)]]

/-- The check items of `(n, a) = (25, 18)`. -/
def items_25_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 13 [(.assumption 9, 23)],
  .gen .cond 288 [(.assumption 10, 215)],
  .direct 2]

/-- The check items of `(n, a) = (25, 19)`. -/
def items_25_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 27 [(.assumption 10, 25)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 20)`. -/
def items_25_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 21)`. -/
def items_25_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 22)`. -/
def items_25_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 23)`. -/
def items_25_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (25, 24)`. -/
def items_25_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 13)`. -/
def items_26_13 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 3979710000 [(.count 2, 94733016840), (.count 3, 38396242080), (.count 4, 10621050048), (.count 5, 4329924480), (.count 6, 3979710000), (.path 7, 353693340), (.path 8, 1238182536), (.priv 8 0, 206281635), (.hall 6 1, 181171560), (.hall 1 2, 692469540), (.hall 6 2, 34566624), (.hall 0 3, 6633380628), (.hall 5 3, 42336534), (.hall 1 4, 59430336), (.hall 4 5, 39721296), (.hall 5 5, 23499240), (.hall 3 9, 1026765180)],
  .gen .cond 5685300000 [(.count 2, 161623982520), (.count 3, 52245632880), (.count 4, 19694788848), (.count 5, 9434565840), (.count 6, 6630196860), (.count 7, 6630196860), (.count 9, 5692577184), (.path 7, 1855673820), (.hall 7 1, 187576998), (.hall 6 2, 70573524), (.hall 7 2, 130799802), (.hall 6 4, 272136360), (.hall 0 5, 323683080), (.hall 5 5, 436946890), (.hall 4 6, 441255084), (.hall 3 8, 1298446716), (.hall 2 10, 4966678080), (.assumption 8, 4776789060)]]

/-- The check items of `(n, a) = (26, 14)`. -/
def items_26_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 658560000 [(.count 2, 34784316000), (.count 3, 6912410400), (.count 4, 1876896000), (.count 5, 756315000), (.count 6, 658854000), (.path 7, 98769000), (.path 8, 164640000), (.priv 7 1, 15120000), (.priv 8 0, 23549400), (.hall 6 2, 5481000), (.hall 5 3, 2786875), (.hall 4 5, 3841600), (.hall 5 6, 4459000)],
  .gen .cond 808500000 [(.count 2, 56192043600), (.count 3, 15451793280), (.count 4, 5117999040), (.count 5, 2180039400), (.count 6, 1318501800), (.count 7, 1229243400), (.count 9, 806818320), (.path 7, 350222400), (.priv 5 5, 67506516), (.priv 5 6, 82685295), (.priv 6 3, 90552000), (.priv 6 4, 255938760), (.priv 6 5, 118728225), (.priv 7 1, 91476000), (.priv 7 2, 80203200), (.priv 8 0, 62674920), (.hall 4 7, 62194132), (.hall 3 9, 283831128), (.hall 2 11, 1127372400), (.assumption 8, 969449712)]]

/-- The check items of `(n, a) = (26, 15)`. -/
def items_26_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1260000 [(.count 2, 92411550), (.count 3, 21552300), (.count 4, 5595975), (.count 5, 1819125), (.count 6, 1262250), (.path 7, 560000)],
  .gen .cond 764400000 [(.count 2, 67260473280), (.count 3, 18848269440), (.count 4, 5862336480), (.count 5, 2436033600), (.count 6, 1419818400), (.count 7, 1190629440), (.path 7, 364017472), (.priv 4 8, 636936300), (.priv 4 9, 1083001920), (.priv 5 5, 25945920), (.priv 5 6, 584936352), (.priv 5 7, 681080400), (.priv 5 8, 98978880), (.priv 6 3, 81510000), (.priv 6 4, 397397000), (.priv 6 5, 122041920), (.priv 7 1, 112612500), (.priv 7 2, 109343520), (.priv 8 0, 102162060), (.priv 9 0, 109549440), (.hall 3 11, 1404202800), (.hall 2 12, 3972386880), (.assumption 8, 1055666976)],
  .gen .cond 501496027200000 [(.count 2, 65704304397251520), (.count 3, 16078263529648320), (.count 4, 3944266253928000), (.count 5, 1003995046454400), (.count 6, 363692083154400), (.count 8, 215141795668800), (.count 10, 537854489172000), (.path 5, 575740137772800), (.path 6, 70599475346400), (.priv 3 10, 189643508774720), (.priv 4 8, 579090000008520), (.priv 4 9, 1135769396301540), (.priv 5 6, 430795833708240), (.priv 5 7, 667451808943920), (.priv 5 8, 716627076525360), (.priv 6 4, 238975294858300), (.priv 6 5, 454444356486120), (.priv 6 6, 142680843655350), (.priv 7 1, 15751452897180), (.priv 7 2, 89203349972880), (.priv 7 3, 243229752325560), (.priv 8 1, 130365683327880), (.priv 9 0, 41662379478720), (.hall 3 11, 2224924736874840), (.hall 2 12, 4660302281564160), (.assumption 9, 215440603718340)]]

/-- The check items of `(n, a) = (26, 16)`. -/
def items_26_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 86730000 [(.count 2, 17171522368), (.count 3, 4370602236), (.count 4, 1213308096), (.count 5, 382702320), (.count 6, 138906768), (.count 7, 84336252), (.path 6, 52033410)],
  .gen .cond 735861000000 [(.count 2, 122769165435840), (.count 3, 28332914951880), (.count 4, 6399164993760), (.count 5, 1486144875600), (.count 6, 431273414880), (.path 4, 584889560640), (.path 5, 944295105600), (.priv 2 14, 11259732939840), (.priv 3 11, 4845674119440), (.priv 3 12, 5354492566500), (.priv 4 8, 928986247728), (.priv 4 9, 2880498450060), (.priv 4 10, 3112162210080), (.priv 4 11, 982021221720), (.priv 5 6, 901076511720), (.priv 5 7, 1603093792608), (.priv 5 8, 1227769361280), (.priv 6 4, 631646262720), (.priv 6 5, 943491539760), (.priv 7 2, 393391290600), (.priv 7 3, 220215865320), (.priv 8 0, 120121949640), (.priv 8 1, 85841864955), (.priv 9 0, 61194200760), (.hall 2 13, 2393373185280), (.assumption 9, 425857477920)],
  .gen .neg 3469200000 [(.count 2, 534195742080), (.count 3, 139452473160), (.count 4, 38185187040), (.count 5, 11126715600), (.count 6, 2806483680), (.path 6, 2775286800), (.priv 3 11, 13047314280), (.priv 4 9, 1653061410), (.priv 5 6, 49609560), (.priv 5 7, 4612271664), (.priv 5 10, 17150733600), (.priv 6 4, 157940640), (.priv 6 6, 12365537184), (.priv 7 7, 10942451520), (.priv 9 1, 141741600), (.priv 10 0, 255134880), (.hall 6 3, 79020942), (.hall 7 3, 257497240), (.hall 8 3, 145285140), (.hall 4 7, 80620904), (.hall 3 10, 1253248500), (.hall 2 12, 5030736480)]]

/-- The check items of `(n, a) = (26, 17)`. -/
def items_26_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 2 [(.assumption 8, 7)],
  .gen .cond 8944824000000 [(.count 2, 3172320294343200), (.count 3, 568116631882800), (.count 4, 92863373803200), (.count 5, 13814386185600), (.count 6, 6331593668400), (.path 4, 58453521654528), (.path 5, 3530396469600), (.priv 2 15, 184671481995000), (.priv 3 11, 49069850930100), (.priv 3 12, 107701047854400), (.priv 3 13, 85764314235600), (.priv 4 8, 12247476641400), (.priv 4 9, 51688828311120), (.priv 4 10, 62524487475450), (.priv 4 11, 7962458704200), (.priv 5 6, 16292204660160), (.priv 5 7, 36070897262400), (.priv 5 8, 8334679665312), (.priv 6 4, 15697075969575), (.priv 6 5, 8675105610600), (.priv 7 2, 8761902349200), (.priv 8 0, 2686130647200), (.priv 9 0, 596917921600), (.assumption 9, 6450048694800)],
  .gen .neg 9392065200000 [(.count 2, 4397195869466400), (.count 3, 742523257476000), (.count 4, 107828958837600), (.count 5, 4604795395200), (.path 4, 84969675895104), (.path 5, 4586395413600), (.priv 2 15, 302861230471800), (.priv 3 11, 51851914814700), (.priv 3 12, 157778197777200), (.priv 3 13, 155411844588000), (.priv 4 8, 11032322301000), (.priv 4 9, 60342006324600), (.priv 4 10, 91280475386100), (.priv 4 11, 58199497356000), (.priv 5 5, 959332374000), (.priv 5 6, 14132336343840), (.priv 5 7, 41046634508880), (.priv 5 8, 46661926671360), (.priv 6 3, 959332374000), (.priv 6 4, 12950987049000), (.priv 6 5, 29684484601200), (.priv 7 2, 15839643419600), (.priv 7 3, 1462981870350), (.priv 8 0, 6513866819460), (.priv 9 0, 2387671686400), (.hall 2 14, 12177125600640)]]

/-- The check items of `(n, a) = (26, 18)`. -/
def items_26_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 13 [(.assumption 9, 23)],
  .gen .cond 288 [(.assumption 10, 215)],
  .direct 2]

/-- The check items of `(n, a) = (26, 19)`. -/
def items_26_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 505 [(.assumption 10, 503)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 20)`. -/
def items_26_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 3 [(.assumption 10, 7)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 21)`. -/
def items_26_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 922 [(.assumption 11, 633)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 22)`. -/
def items_26_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 23)`. -/
def items_26_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 24)`. -/
def items_26_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (26, 25)`. -/
def items_26_25 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 14)`. -/
def items_27_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1564073280000 [(.count 2, 86131560438000), (.count 3, 16041526578000), (.count 4, 4375495000800), (.count 5, 1772616384000), (.count 6, 1564073280000), (.path 7, 207364657500), (.path 8, 418277882880), (.priv 7 0, 81607618125), (.priv 8 0, 59700118500), (.hall 5 3, 14883005500), (.hall 4 5, 3398135400), (.hall 5 5, 1267189000), (.hall 4 8, 102186120960), (.hall 3 9, 113039841600)],
  .gen .cond 924000000 [(.count 2, 112058100000), (.count 3, 27313070400), (.count 4, 8145023040), (.count 5, 3127924800), (.count 6, 1772555400), (.count 7, 1708522200), (.path 8, 506510928), (.priv 6 3, 41071800), (.priv 7 1, 65518200), (.priv 8 0, 162716400), (.priv 9 0, 153938400), (.hall 6 3, 29074815), (.hall 5 5, 32124400), (.hall 6 6, 21049875), (.hall 4 7, 90150984), (.hall 5 8, 548055200), (.hall 3 9, 248300640), (.assumption 8, 1772827056)]]

/-- The check items of `(n, a) = (27, 15)`. -/
def items_27_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1550132640000 [(.count 2, 95061884148000), (.count 3, 17904031992000), (.count 4, 4547055744000), (.count 5, 1823558814000), (.count 6, 1552900734000), (.path 7, 270646992000), (.path 8, 369071510850), (.priv 5 5, 168146332200), (.priv 5 6, 52575332040), (.priv 6 3, 144512082000), (.priv 7 0, 33832260000), (.priv 8 0, 46181034900), (.hall 6 2, 8082151000), (.hall 4 6, 1911010080), (.hall 3 9, 27127321200)],
  .gen .pos 4480000 [(.count 2, 506721600), (.count 3, 134386560), (.count 4, 35851200), (.count 5, 12150600), (.count 6, 5108400), (.count 7, 4481400), (.path 8, 640080), (.path 9, 640000), (.priv 8 0, 4620), (.priv 9 0, 92400), (.hall 9 1, 240240), (.hall 7 3, 12045)],
  .gen .cond 145431000000 [(.count 2, 15956805664800), (.count 3, 4345792410960), (.count 4, 1343130909120), (.count 5, 457496839800), (.count 6, 171637666200), (.count 7, 69123354300), (.count 8, 84373248960), (.count 10, 145372827600), (.path 6, 87259372200), (.priv 4 8, 49455265860), (.priv 4 9, 280198999080), (.priv 5 6, 51507588132), (.priv 5 7, 145194674625), (.priv 5 8, 242145523620), (.priv 6 4, 33051618600), (.priv 6 5, 87773425740), (.priv 6 6, 122747399775), (.priv 7 2, 15648375600), (.priv 7 3, 60368408100), (.priv 7 4, 25185740580), (.priv 8 1, 36139603500), (.priv 9 0, 11686835160), (.hall 4 10, 148534233120), (.hall 3 11, 820501341660), (.hall 2 12, 1227446589600), (.assumption 9, 84555360890)]]

/-- The check items of `(n, a) = (27, 16)`. -/
def items_27_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 8400000 [(.count 2, 831350520), (.count 3, 176576400), (.count 4, 41981940), (.count 5, 12612600), (.count 6, 8365500), (.path 7, 4199832), (.priv 8 0, 150150), (.hall 8 5, 57915), (.hall 6 8, 85800)],
  .gen .pos 630000 [(.count 2, 83135052), (.count 3, 22666644), (.count 4, 6306300), (.count 5, 1981980), (.count 6, 810810), (.count 7, 630630), (.path 8, 180012)],
  .gen .cond 21798000000 [(.count 2, 3059874195840), (.count 3, 784707073920), (.count 4, 242501878080), (.count 5, 81716342400), (.count 6, 29924294400), (.count 7, 15307427520), (.count 10, 24169622400), (.path 6, 13661524800), (.priv 2 14, 265865846400), (.priv 3 11, 69286250880), (.priv 3 12, 143003599200), (.priv 4 9, 61632537120), (.priv 4 10, 78719117400), (.priv 4 11, 86557460220), (.priv 5 6, 4690057680), (.priv 5 7, 34044639552), (.priv 5 8, 48209764680), (.priv 5 9, 23862706560), (.priv 6 4, 4761306000), (.priv 6 5, 19925551800), (.priv 6 6, 23085825840), (.priv 7 2, 3006816120), (.priv 7 3, 14460668640), (.priv 7 4, 661787280), (.priv 8 0, 1253239680), (.priv 8 1, 4972396275), (.priv 9 0, 1779152760), (.hall 2 13, 109971781920), (.assumption 9, 16274483680)],
  .gen .neg 340409193600000 [(.count 2, 52791849175665600), (.count 3, 13712737586708160), (.count 4, 3745811704995360), (.count 5, 1079619914973600), (.count 6, 265993312384800), (.path 5, 11850020582400), (.path 6, 267603200504640), (.priv 2 14, 6856368793354080), (.priv 3 11, 1262396147492480), (.priv 3 12, 3027803613394560), (.priv 4 9, 983001755916180), (.priv 4 10, 1642291389178440), (.priv 4 11, 2144897053299000), (.priv 5 6, 12169628671200), (.priv 5 7, 539914268589696), (.priv 5 8, 923414038386840), (.priv 5 9, 1234348050936000), (.priv 6 4, 16143384972000), (.priv 6 5, 264254794003200), (.priv 6 6, 553544252701440), (.priv 6 7, 472007740604400), (.priv 7 2, 6519443931000), (.priv 7 3, 130686910342560), (.priv 7 4, 347529824481840), (.priv 7 5, 81779904670464), (.priv 8 0, 3245234312320), (.priv 8 1, 39018871927035), (.priv 8 2, 184109096611440), (.priv 9 0, 80319549229920), (.priv 10 0, 28163997781920), (.hall 3 12, 503260951818240), (.hall 2 13, 2832046443626400)]]

/-- The check items of `(n, a) = (27, 17)`. -/
def items_27_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .cond 9 [(.assumption 8, 22)],
  .gen .cond 3515842814400000 [(.count 2, 846053821194341760), (.count 3, 211689423231446160), (.count 4, 54449506082331360), (.count 5, 16716953621768400), (.count 6, 5429867642559360), (.count 7, 2111615194328640), (.path 5, 1489072802817600), (.path 6, 2316645813081600), (.priv 2 15, 74258467667223840), (.priv 3 12, 34049795008549320), (.priv 3 13, 36029434253232420), (.priv 4 9, 7269989454760032), (.priv 4 10, 20588248144704240), (.priv 4 11, 20776785215626440), (.priv 4 12, 2488689336173040), (.priv 5 6, 82597192975440), (.priv 5 7, 7591759389133920), (.priv 5 8, 11613883568807520), (.priv 5 9, 4776272463362400), (.priv 6 4, 433635263121060), (.priv 6 5, 5720753409125040), (.priv 6 6, 3758172280382520), (.priv 7 2, 414781556028840), (.priv 7 3, 3176849645039070), (.priv 8 0, 105580759716432), (.priv 8 1, 1046031600894280), (.priv 9 0, 351935865721440), (.priv 10 0, 395927848936620), (.hall 2 14, 12998164640645184), (.assumption 9, 3152392563461400)],
  .gen .neg 141120000 [(.count 2, 24256552320), (.count 3, 2875672800), (.count 9, 2815132320), (.count 10, 908107200), (.path 3, 2874551680), (.priv 2 12, 479278800), (.priv 2 13, 4338734400), (.priv 2 14, 6407200800), (.priv 2 15, 6407200800), (.priv 3 9, 176996820), (.priv 3 10, 1388899512), (.priv 3 11, 1587295710), (.priv 3 12, 3129606480), (.priv 3 13, 2266484220), (.priv 4 6, 70675605), (.priv 4 7, 299150280), (.priv 4 8, 480720240), (.priv 4 9, 1018161144), (.priv 4 10, 1293782490), (.priv 4 11, 908827920), (.priv 5 3, 23567544), (.priv 5 4, 61661600), (.priv 5 5, 123243120), (.priv 5 6, 334414080), (.priv 5 7, 550990440), (.priv 5 8, 579603024), (.priv 6 1, 40622400), (.priv 6 2, 27531504), (.priv 6 3, 98578480), (.priv 6 4, 228828600), (.priv 6 5, 259562160), (.priv 7 0, 98771400), (.priv 7 1, 132324192), (.priv 8 0, 92828736), (.hall 2 14, 492395904)]]

/-- The check items of `(n, a) = (27, 18)`. -/
def items_27_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 13 [(.assumption 9, 23)],
  .gen .cond 863688000000 [(.count 2, 707549101459200), (.count 3, 90870557778000), (.count 4, 8707270572000), (.count 5, 333469936800), (.path 3, 26979605452800), (.path 4, 7908076915200), (.priv 2 16, 41563322400600), (.priv 3 12, 12926591577900), (.priv 3 13, 21465583339200), (.priv 3 14, 19220836635000), (.priv 4 9, 3249788041500), (.priv 4 10, 10354241537640), (.priv 4 11, 11965549746150), (.priv 4 12, 3621854035800), (.priv 5 6, 261218117160), (.priv 5 7, 3170610986400), (.priv 5 8, 6560712238080), (.priv 5 9, 3171669621120), (.priv 6 4, 226430204000), (.priv 6 5, 2857652097300), (.priv 6 6, 2371341772800), (.priv 7 2, 190818908280), (.priv 7 3, 1906130626400), (.priv 8 0, 383153589000), (.priv 8 1, 337175158320), (.priv 9 0, 259365506400), (.assumption 10, 334469347200)],
  .gen .cond 43 [(.assumption 11, 19)]]

/-- The check items of `(n, a) = (27, 19)`. -/
def items_27_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 758 [(.assumption 10, 755)],
  .gen .cond 379 [(.assumption 11, 162)],
  .direct 2]

/-- The check items of `(n, a) = (27, 20)`. -/
def items_27_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 214 [(.assumption 10, 335)],
  .gen .cond 504 [(.assumption 11, 359)],
  .direct 2]

/-- The check items of `(n, a) = (27, 21)`. -/
def items_27_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 998 [(.assumption 11, 939)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 22)`. -/
def items_27_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 23)`. -/
def items_27_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 24)`. -/
def items_27_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 25)`. -/
def items_27_25 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (27, 26)`. -/
def items_27_26 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 14)`. -/
def items_28_14 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 708960000 [(.count 2, 22869277200), (.count 3, 9826185600), (.count 4, 2339568000), (.count 5, 861386400), (.count 6, 708960000), (.path 7, 153676250), (.path 8, 160655400), (.priv 8 0, 22946250), (.hall 6 1, 28896450), (.hall 1 2, 222879300), (.hall 0 3, 1625733900), (.hall 5 3, 4214725), (.hall 6 3, 1133070), (.hall 1 5, 4615625), (.hall 5 5, 1709100), (.hall 4 6, 4785480), (.hall 3 10, 170150400)],
  .gen .pos 15750000 [(.count 2, 1350518400), (.count 3, 441163800), (.count 4, 110224800), (.count 5, 36741600), (.count 6, 15724800), (.count 7, 15743700), (.path 9, 5250000), (.priv 4 10, 8580600), (.priv 9 0, 875000), (.priv 10 0, 1400112), (.hall 7 1, 492450), (.hall 0 2, 415800), (.hall 7 2, 218820), (.hall 1 3, 109620), (.hall 6 3, 84420), (.hall 0 4, 6713280), (.hall 1 4, 498960), (.hall 0 5, 5174400), (.hall 6 5, 156300), (.hall 8 5, 436800), (.hall 5 7, 273000), (.hall 4 8, 2370480), (.hall 1 11, 7692300)]]

/-- The check items of `(n, a) = (28, 15)`. -/
def items_28_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 300767040000 [(.count 2, 19621791050400), (.count 3, 3664094464800), (.count 4, 919745608320), (.count 5, 358414056000), (.count 6, 300516400800), (.path 7, 58017960000), (.path 8, 68173862400), (.priv 5 5, 26896371040), (.priv 5 6, 25658770368), (.priv 6 2, 14560571025), (.priv 6 3, 11618917200), (.priv 7 0, 12494165200), (.priv 8 0, 8529565275), (.hall 3 9, 5551658280), (.hall 4 9, 4992732864)],
  .gen .pos 120960000 [(.count 2, 14819112000), (.count 3, 3268188000), (.count 4, 838252800), (.count 5, 280526400), (.count 6, 120582000), (.count 7, 120582000), (.path 9, 38880000), (.priv 8 0, 4054050), (.priv 9 0, 5544000), (.hall 6 3, 1146750), (.hall 7 3, 478170), (.hall 5 5, 1965040), (.hall 4 7, 2147040)],
  .gen .cond 3200125500000 [(.count 2, 283272549159600), (.count 3, 82094739526800), (.count 4, 27031588103520), (.count 5, 10429849029600), (.count 6, 4744506066300), (.count 7, 3481096518900), (.count 8, 2419294878000), (.count 10, 3225726504000), (.path 7, 1066701636000), (.priv 5 6, 82435232880), (.priv 6 4, 73922899050), (.priv 6 5, 1246384879740), (.priv 7 3, 814751952300), (.priv 7 4, 1420087691880), (.priv 8 1, 533460920850), (.priv 8 2, 254623318950), (.priv 9 0, 247305698640), (.hall 5 6, 108014902710), (.hall 5 7, 90350209950), (.hall 4 8, 577242128736), (.hall 3 10, 2728427001300), (.hall 2 12, 21790196089200), (.assumption 9, 2411728359040)]]

/-- The check items of `(n, a) = (28, 16)`. -/
def items_28_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 6834240000 [(.count 2, 604946422080), (.count 3, 109359458208), (.count 4, 26061235200), (.count 5, 8877108240), (.count 6, 6841074240), (.path 7, 2061079020), (.path 8, 1084821696), (.priv 3 13, 6156966816), (.priv 7 2, 98893080), (.priv 8 0, 121257136), (.hall 6 2, 22234784), (.hall 5 3, 1480752), (.hall 4 6, 15888704), (.hall 5 6, 8531952)],
  .gen .pos 7280000 [(.count 2, 1280779500), (.count 3, 305855550), (.count 4, 84884800), (.count 5, 24274250), (.count 6, 9759750), (.count 7, 7257250), (.path 8, 2426550)],
  .gen .cond 647829000000 [(.count 2, 93585895603200), (.count 3, 27244578160800), (.count 4, 8565024948480), (.count 5, 3061380722400), (.count 6, 1355998644000), (.count 7, 1145879935200), (.count 10, 615696681600), (.path 7, 259151092200), (.priv 2 14, 1949706158400), (.priv 4 9, 604579935960), (.priv 4 10, 1795781988000), (.priv 5 7, 529157092464), (.priv 5 8, 994948734780), (.priv 5 9, 1421803262880), (.priv 6 5, 353251899000), (.priv 6 6, 626691265200), (.priv 6 7, 405272567700), (.priv 7 3, 231584324400), (.priv 7 4, 303776272800), (.priv 8 0, 54918623760), (.priv 8 1, 118436097780), (.priv 9 0, 51308056800), (.hall 3 11, 103602807000), (.hall 4 11, 240577777440), (.hall 3 12, 3317657888160), (.hall 2 13, 8370542980800), (.assumption 9, 611826983040)],
  .gen .neg 86732704800000 [(.count 2, 24557498037072000), (.count 3, 4450116310960320), (.count 4, 668096242894080), (.count 5, 23771988840600), (.count 11, 68215272325200), (.path 4, 548216476647840), (.path 5, 23954765234400), (.priv 2 14, 2567374794784800), (.priv 3 11, 696209203609920), (.priv 4 8, 110550083756112), (.priv 4 9, 344590481715480), (.priv 4 10, 475439776812000), (.priv 5 5, 7855091964720), (.priv 5 6, 71005897102140), (.priv 5 7, 154455913579968), (.priv 5 8, 237926601352440), (.priv 5 9, 330051671149200), (.priv 6 3, 3359085379650), (.priv 6 4, 33791238795600), (.priv 6 5, 79510658327100), (.priv 6 6, 128162026792800), (.priv 6 7, 123880115759400), (.priv 7 1, 1689796308200), (.priv 7 2, 12384320273325), (.priv 7 3, 44612028747000), (.priv 7 4, 81922309368900), (.priv 7 5, 8888656696920), (.priv 8 1, 33797566742940), (.priv 8 2, 24185414733480), (.priv 9 0, 21291433483320), (.priv 10 0, 7087301020800), (.hall 3 11, 18389501735220), (.hall 4 11, 73589808932640), (.hall 3 12, 910745440022880), (.hall 2 13, 2461065279472800)]]

/-- The check items of `(n, a) = (28, 17)`. -/
def items_28_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 20000 [(.count 2, 6864858), (.count 3, 1679678), (.count 4, 420420), (.count 5, 120120), (.count 6, 44330), (.count 7, 32032), (.path 7, 12000), (.priv 7 10, 158444)],
  .gen .cond 4463978400000 [(.count 2, 1606341200143680), (.count 3, 371519066318400), (.count 4, 99773934820560), (.count 5, 28315333846800), (.count 6, 9301655563200), (.count 7, 4596112160640), (.count 8, 1532037386880), (.path 6, 4722027710400), (.priv 3 12, 16171505750400), (.priv 3 13, 46152626279760), (.priv 4 9, 2183153276304), (.priv 4 10, 20371309628670), (.priv 4 11, 23395487595480), (.priv 4 12, 19677105187740), (.priv 5 7, 4828653549720), (.priv 5 8, 11561410708848), (.priv 5 9, 14212382544360), (.priv 6 5, 4543350669000), (.priv 6 6, 7295416128000), (.priv 6 7, 930165556320), (.priv 7 3, 3604391530740), (.priv 7 4, 1059138091440), (.priv 8 1, 1478841644280), (.priv 9 0, 482308066240), (.priv 10 0, 574514020080), (.hall 2 14, 22674153325824), (.assumption 9, 4507390589940)],
  .gen .cond 1647293760000 [(.count 2, 564644529408960), (.count 3, 121707553968000), (.count 4, 25008939315360), (.count 5, 4458871216800), (.count 6, 560864304000), (.path 5, 3875444773200), (.priv 2 15, 59244096431520), (.priv 3 12, 17789369357760), (.priv 3 13, 25035112982880), (.priv 4 9, 2606897284992), (.priv 4 10, 10389310151220), (.priv 4 11, 13306038225480), (.priv 4 12, 14933713174380), (.priv 5 7, 2375260327440), (.priv 5 8, 5150977767936), (.priv 5 9, 7373963436840), (.priv 5 10, 4786042060800), (.priv 6 5, 1426865497200), (.priv 6 6, 3023214394200), (.priv 6 7, 3997092939840), (.priv 7 3, 677944727460), (.priv 7 4, 2119265834400), (.priv 7 5, 663689426400), (.priv 8 1, 199574214840), (.priv 8 2, 1098067145175), (.priv 9 0, 427503236160), (.priv 10 0, 132504191820), (.hall 3 13, 61695073440), (.hall 2 14, 19017786820032), (.assumption 10, 555595578720)]]

/-- The check items of `(n, a) = (28, 18)`. -/
def items_28_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 2852805600000 [(.count 2, 1263343278637440), (.count 3, 283352705295660), (.count 4, 75674947748400), (.count 5, 21179466508200), (.count 6, 6853580173440), (.count 7, 2998441325880), (.path 5, 406436530500), (.path 6, 3226173350400), (.priv 2 16, 92618520954960), (.priv 3 12, 7954198517265), (.priv 3 13, 44865566505760), (.priv 3 14, 43060949041110), (.priv 4 10, 17319568229964), (.priv 4 11, 25879404300750), (.priv 4 12, 18347605255980), (.priv 5 7, 2821662472200), (.priv 5 8, 12723544673840), (.priv 5 9, 11746274908368), (.priv 6 5, 3902733154320), (.priv 6 6, 6656403759720), (.priv 7 3, 3537843469160), (.priv 8 1, 1066112471424), (.priv 9 0, 199896088392), (.priv 9 6, 166580073660), (.hall 2 15, 10744414751070), (.assumption 9, 3209370639930)],
  .gen .cond 1162308000000 [(.count 2, 715115390109120), (.count 3, 132146957582640), (.count 4, 25489972347840), (.count 5, 4288219135200), (.count 6, 598356158400), (.path 4, 3021480221760), (.path 5, 2955494341800), (.priv 2 16, 59476602144960), (.priv 3 12, 3952890371430), (.priv 3 13, 24642301123440), (.priv 3 14, 26980876442520), (.priv 4 10, 7679901293064), (.priv 4 11, 13810808081070), (.priv 4 12, 14849205330960), (.priv 4 13, 3575178046440), (.priv 5 7, 765041088240), (.priv 5 8, 5272182595680), (.priv 5 9, 7748712251280), (.priv 5 10, 4722027350040), (.priv 6 5, 766643827950), (.priv 6 6, 3424876678080), (.priv 6 7, 3590136950400), (.priv 7 3, 553479446520), (.priv 7 4, 2428952030505), (.priv 8 1, 345550681476), (.priv 8 2, 717473356600), (.priv 9 0, 335079448704), (.priv 10 0, 139616436960), (.hall 2 15, 10017479351880), (.assumption 10, 623043580320)],
  .gen .neg 85136940000 [(.count 2, 74605841069760), (.count 3, 13343342332320), (.count 4, 2281864590720), (.count 5, 336250371600), (.path 3, 1115366452200), (.path 5, 337857577200), (.priv 3 13, 2551251382680), (.priv 4 11, 2247514876035), (.priv 5 11, 4581121442040), (.priv 6 5, 11594840400), (.priv 7 3, 193247340), (.hall 8 2, 360728368), (.hall 6 4, 8538018840), (.hall 7 4, 2717760318), (.hall 9 4, 2318968080), (.hall 8 5, 7729893600), (.hall 7 6, 4181169720), (.hall 5 7, 5819717970), (.hall 3 12, 52676251848), (.hall 2 14, 410553973830)]]

/-- The check items of `(n, a) = (28, 19)`. -/
def items_28_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 221104800000 [(.count 2, 237372032898000), (.count 3, 35807369598000), (.count 4, 4837551919200), (.count 6, 142280938800), (.path 4, 3858547492800), (.priv 2 16, 7884735358500), (.priv 2 17, 15714139240800), (.priv 3 13, 6386833252800), (.priv 3 14, 9564440886000), (.priv 3 15, 6125984865000), (.priv 4 9, 98241600600), (.priv 4 10, 1547963917500), (.priv 4 11, 4703175477000), (.priv 4 12, 4821742926000), (.priv 4 13, 5269664400), (.priv 5 3, 6323597280), (.priv 5 6, 48480912480), (.priv 5 7, 212630958540), (.priv 5 8, 1547474591520), (.priv 5 9, 2910962614560), (.priv 5 10, 145442737440), (.priv 6 5, 304762257800), (.priv 6 6, 1437630319125), (.priv 6 7, 189707918400), (.priv 7 3, 382577635440), (.priv 7 4, 330232302400), (.priv 8 1, 231386173200), (.priv 9 0, 80482147200), (.assumption 10, 146730672900)],
  .gen .cond 288 [(.assumption 11, 215)],
  .direct 2]

/-- The check items of `(n, a) = (28, 20)`. -/
def items_28_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 214 [(.assumption 10, 335)],
  .gen .cond 504 [(.assumption 11, 359)],
  .direct 2]

/-- The check items of `(n, a) = (28, 21)`. -/
def items_28_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 203 [(.assumption 11, 191)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 22)`. -/
def items_28_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 5 [(.assumption 11, 12)],
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 23)`. -/
def items_28_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 563 [(.assumption 12, 375)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 24)`. -/
def items_28_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 25)`. -/
def items_28_25 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 26)`. -/
def items_28_26 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (28, 27)`. -/
def items_28_27 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 15)`. -/
def items_29_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 218756160000 [(.count 2, 20275633445760), (.count 3, 3229278433920), (.count 4, 770021683200), (.count 5, 274320224640), (.count 6, 218974916160), (.path 7, 55293638400), (.path 8, 43262676576), (.priv 7 0, 8522375400), (.priv 8 0, 5414214960), (.hall 5 3, 1231805520), (.hall 5 5, 105037680), (.hall 4 6, 871899552), (.hall 3 10, 13284879300)],
  .gen .pos 40320000 [(.count 2, 5766647040), (.count 3, 1128813840), (.count 4, 282078720), (.count 5, 94137120), (.count 6, 40360320), (.count 7, 40360320), (.path 9, 13439520), (.priv 8 0, 696465), (.priv 8 3, 2866248), (.priv 9 0, 1921920), (.priv 9 5, 1404480), (.priv 10 2, 5305608), (.hall 6 3, 354200), (.hall 5 5, 428208), (.hall 6 5, 288200), (.hall 7 6, 1046430), (.hall 4 8, 1084608)],
  .gen .cond 686400000 [(.count 2, 63169666560), (.count 3, 19169710560), (.count 4, 6425939520), (.count 5, 2503781280), (.count 6, 1222341120), (.count 7, 857656800), (.count 8, 859098240), (.count 10, 683242560), (.path 8, 191187360), (.priv 9 0, 50244480), (.hall 7 3, 24882858), (.hall 6 4, 13970528), (.hall 5 6, 39510900), (.hall 6 6, 34388640), (.hall 7 7, 10090080), (.hall 4 8, 99450624), (.hall 3 10, 403783380), (.hall 2 12, 2275922880), (.assumption 9, 667578912)]]

/-- The check items of `(n, a) = (29, 16)`. -/
def items_29_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 11243912400000 [(.count 2, 1024058436481080), (.count 3, 171721527737760), (.count 4, 40904453798208), (.count 5, 14363723293920), (.count 6, 11255156312400), (.path 7, 3066450987600), (.path 8, 2044518071400), (.priv 5 6, 1118369500248), (.priv 6 5, 140689453905), (.priv 6 8, 1715071438080), (.priv 7 3, 523381175460), (.priv 8 0, 227782925370), (.hall 5 5, 6071117780), (.hall 4 6, 14129849916), (.hall 3 10, 200141640720)],
  .gen .pos 2358720000 [(.count 2, 337134798000), (.count 3, 66324258000), (.count 4, 16605388800), (.count 5, 5513508000), (.count 6, 2378376000), (.count 7, 2351349000), (.path 8, 8316000), (.path 9, 777886200), (.priv 3 13, 324324000), (.priv 5 7, 611170560), (.priv 5 8, 625224600), (.priv 6 4, 148648500), (.priv 6 5, 464714250), (.priv 6 6, 151351200), (.priv 7 2, 265926375), (.priv 8 0, 119619500), (.priv 9 0, 97297200), (.hall 9 1, 194594400), (.hall 4 10, 126289800), (.hall 3 11, 451143000)],
  .gen .cond 2548000000 [(.count 2, 435639204000), (.count 3, 114421507200), (.count 4, 37292935680), (.count 5, 13722508800), (.count 6, 6180174000), (.count 7, 3935131200), (.count 8, 3565161600), (.count 10, 2572970400), (.path 8, 849307200), (.priv 5 7, 660563904), (.priv 5 8, 2734411680), (.priv 6 5, 613112500), (.priv 6 6, 1646364720), (.priv 6 7, 2610808200), (.priv 7 3, 451479600), (.priv 7 4, 1111110000), (.priv 7 5, 423783360), (.priv 8 1, 358408050), (.priv 8 2, 282282000), (.priv 9 0, 190870680), (.hall 4 9, 256838400), (.hall 4 10, 196297920), (.hall 5 10, 620692800), (.hall 3 11, 2630212200), (.hall 2 13, 21603582000), (.assumption 9, 3086952960)],
  .gen .cond 1467062856000000 [(.count 2, 245307433445474400), (.count 3, 65328602390251200), (.count 4, 20114664088559040), (.count 5, 6545447638329600), (.count 6, 2160836880602400), (.count 7, 1426571921174400), (.count 9, 553845569397120), (.count 11, 1384613923492800), (.path 6, 254384033389200), (.path 7, 452161753243200), (.priv 2 14, 5884609174844400), (.priv 5 7, 167272550757312), (.priv 5 8, 1902095894899200), (.priv 6 5, 93531369831900), (.priv 6 6, 923075948995200), (.priv 6 7, 2157777443271450), (.priv 7 4, 472526973890400), (.priv 7 5, 1236861831656880), (.priv 7 6, 834289828901100), (.priv 8 1, 69274402422225), (.priv 8 2, 82916995418400), (.priv 8 3, 809439705274200), (.priv 8 4, 41608347700920), (.priv 9 1, 359639980128000), (.priv 10 0, 111488393839680), (.hall 5 9, 564525786988800), (.hall 4 10, 1574187785745120), (.hall 3 11, 2356909831306800), (.hall 2 13, 22994481229434000), (.assumption 10, 554248196647600)]]

/-- The check items of `(n, a) = (29, 17)`. -/
def items_29_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 4320000 [(.count 2, 1111350240), (.count 3, 253837584), (.count 4, 60540480), (.count 5, 17297280), (.count 6, 6074640), (.count 7, 4324320), (.path 8, 1728000), (.priv 7 8, 154440), (.priv 8 2, 705705)],
  .gen .cond 1274000000 [(.count 2, 321469948800), (.count 3, 86769642960), (.count 4, 24579434880), (.count 5, 8778369600), (.count 6, 3762158400), (.count 7, 2270268000), (.count 8, 1755673920), (.path 8, 504924840), (.priv 3 12, 151351200), (.priv 4 10, 2429186760), (.priv 4 11, 5009724720), (.priv 5 7, 20180160), (.priv 5 8, 2070484416), (.priv 5 9, 2796213420), (.priv 5 10, 2969006040), (.priv 6 5, 194594400), (.priv 6 6, 1203602400), (.priv 6 7, 1816214400), (.priv 6 8, 109459350), (.priv 7 3, 237161925), (.priv 7 4, 803088000), (.priv 7 5, 196396200), (.priv 8 1, 248888640), (.priv 8 2, 144729585), (.priv 9 0, 149669520), (.priv 10 0, 158918760), (.hall 3 13, 10002152160), (.hall 2 14, 21128627520), (.assumption 9, 1767104640)],
  .gen .cond 238329000000 [(.count 2, 83858251276800), (.count 3, 20585791306080), (.count 4, 5085521400960), (.count 5, 1394701308000), (.count 6, 352345593600), (.count 7, 117448531200), (.count 8, 70469118720), (.count 9, 118916637840), (.count 11, 242237595600), (.path 6, 226873286640), (.priv 2 15, 2840786348400), (.priv 3 12, 438963885360), (.priv 4 10, 714967933680), (.priv 4 11, 1491596346240), (.priv 5 8, 478015521984), (.priv 5 9, 785987592390), (.priv 5 10, 1186719534000), (.priv 6 5, 14531259600), (.priv 6 6, 238567329000), (.priv 6 7, 464341157280), (.priv 6 8, 542806213950), (.priv 7 3, 2949321375), (.priv 7 4, 126511842600), (.priv 7 5, 280076296500), (.priv 7 6, 119650691160), (.priv 8 2, 51475489065), (.priv 8 3, 146181475440), (.priv 9 1, 65697772140), (.priv 10 0, 18167819670), (.hall 4 12, 441335442240), (.hall 3 13, 3701516298480), (.hall 2 14, 6976442753280), (.assumption 10, 124887926800)]]

/-- The check items of `(n, a) = (29, 18)`. -/
def items_29_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .pos 87935680000 [(.count 2, 70190031143232), (.count 3, 15192876066368), (.count 4, 3688189496992), (.count 5, 899098360160), (.count 6, 238921242560), (.count 7, 88023615680), (.count 8, 88023615680), (.path 5, 90476946560), (.path 6, 61984914420)],
  .gen .cond 6595176000000 [(.count 2, 3759840720155520), (.count 3, 796965816366720), (.count 4, 164780208552960), (.count 5, 33951966048000), (.count 6, 5658661008000), (.count 7, 3564956435040), (.path 5, 16297583702400), (.path 6, 1476898233525), (.priv 2 16, 366002193997440), (.priv 3 13, 126225864885120), (.priv 3 14, 154085339247840), (.priv 4 10, 23310854022456), (.priv 4 11, 68724437942160), (.priv 4 12, 81498865167720), (.priv 4 13, 73428199905060), (.priv 5 7, 929637165600), (.priv 5 8, 19644984799440), (.priv 5 9, 34585736080896), (.priv 5 10, 44802448530840), (.priv 5 11, 12449054217600), (.priv 6 5, 1090471131750), (.priv 6 6, 12199803673200), (.priv 6 7, 21330008299600), (.priv 6 8, 12505640827680), (.priv 7 3, 282933050400), (.priv 7 4, 7950418716240), (.priv 7 5, 9991578579840), (.priv 8 2, 4995340189840), (.priv 8 3, 1373993626005), (.priv 9 0, 1874903013984), (.priv 10 0, 528141694080), (.hall 2 15, 100561479438420), (.assumption 10, 4228958754720)],
  .gen .neg 15664320000 [(.count 2, 8399991600000), (.count 3, 1962238037760), (.count 4, 508479491520), (.count 5, 130399869600), (.count 6, 31199968800), (.count 7, 4479995520), (.path 6, 12935604825), (.path 7, 4563072360), (.priv 2 16, 1028158971840), (.priv 3 13, 222008666880), (.priv 3 14, 450612882720), (.priv 4 10, 5655994344), (.priv 4 11, 162119837880), (.priv 4 12, 237066429600), (.priv 4 13, 308979691020), (.priv 5 8, 13333320000), (.priv 5 9, 79551920448), (.priv 5 10, 132599867400), (.priv 5 11, 160799839200), (.priv 6 6, 10780941600), (.priv 6 7, 40444404000), (.priv 6 8, 75573257760), (.priv 6 9, 55766610900), (.priv 7 4, 6539993460), (.priv 7 5, 23954261760), (.priv 7 6, 46586620080), (.priv 8 2, 3266663400), (.priv 8 3, 16449983550), (.priv 8 4, 11519988480), (.priv 9 0, 2165331168), (.priv 9 1, 8877028160), (.priv 10 0, 4106662560), (.hall 3 14, 40618626048), (.hall 2 15, 350699649300)]]

/-- The check items of `(n, a) = (29, 19)`. -/
def items_29_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .cond 5 [(.assumption 9, 14)],
  .gen .cond 3555891360000 [(.count 2, 3794370769949760), (.count 3, 712779312084840), (.count 4, 136275980480640), (.count 5, 23729648342400), (.count 6, 4576432180320), (.count 7, 2669585438520), (.path 5, 16196848668000), (.priv 2 17, 281196332857440), (.priv 3 13, 32776576772940), (.priv 3 14, 123097550776200), (.priv 3 15, 125173895006160), (.priv 4 10, 5868850527540), (.priv 4 11, 45103281599376), (.priv 4 12, 67820182450020), (.priv 4 13, 62925942479400), (.priv 5 8, 10327239814320), (.priv 5 9, 29831557916160), (.priv 5 10, 38323382072976), (.priv 5 11, 2839082926680), (.priv 6 5, 56499162720), (.priv 6 6, 9746105569200), (.priv 6 7, 20339698579200), (.priv 6 8, 2627211066480), (.priv 7 4, 8658496686840), (.priv 7 5, 3464104914270), (.priv 8 2, 4004378157780), (.priv 9 0, 1078620379200), (.hall 2 16, 35454886346880), (.assumption 10, 2786548865040)],
  .gen .neg 115012800000 [(.count 2, 102723613312320), (.count 3, 9792853990920), (.path 3, 9800444253600), (.priv 2 15, 9254631466080), (.priv 2 16, 17181181377360), (.priv 2 17, 17195161183200), (.priv 3 11, 356485048920), (.priv 3 12, 3528502994016), (.priv 3 13, 4269083208390), (.priv 3 14, 8315654507160), (.priv 3 15, 6025296317040), (.priv 4 8, 233288009955), (.priv 4 9, 816106828680), (.priv 4 10, 1292632761420), (.priv 4 11, 2698501950144), (.priv 4 12, 3356651237940), (.priv 4 13, 2318650654320), (.priv 5 5, 77687778168), (.priv 5 6, 194163970000), (.priv 5 7, 367968460860), (.priv 5 8, 914678724960), (.priv 5 9, 1436258623800), (.priv 5 10, 1392388661664), (.priv 6 2, 5991345360), (.priv 6 4, 331720821432), (.priv 6 5, 197048691840), (.priv 6 6, 640824314130), (.priv 6 7, 540932895360), (.priv 7 0, 8987018040), (.priv 7 2, 413130495960), (.priv 7 3, 197115262344), (.priv 8 0, 237656699280), (.priv 9 0, 99129532320), (.priv 10 0, 25163650512), (.hall 2 16, 1144699395840)],
  .direct 2]

/-- The check items of `(n, a) = (29, 20)`. -/
def items_29_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 214 [(.assumption 10, 335)],
  .gen .cond 505 [(.assumption 11, 503)],
  .gen .cond 503 [(.assumption 12, 215)]]

/-- The check items of `(n, a) = (29, 21)`. -/
def items_29_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 183 [(.assumption 11, 223)],
  .gen .cond 579 [(.assumption 12, 241)],
  .direct 2]

/-- The check items of `(n, a) = (29, 22)`. -/
def items_29_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 915 [(.assumption 11, 1642)],
  .gen .cond 855 [(.assumption 12, 587)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 23)`. -/
def items_29_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 247 [(.assumption 12, 222)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 24)`. -/
def items_29_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 25)`. -/
def items_29_25 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 26)`. -/
def items_29_26 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 27)`. -/
def items_29_27 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (29, 28)`. -/
def items_29_28 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 15)`. -/
def items_30_15 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1680000 [(.count 2, 137297160), (.count 3, 50478120), (.count 4, 12113640), (.count 5, 3931200), (.count 6, 1678320), (.count 7, 1681680), (.path 9, 576480), (.priv 7 2, 4440), (.priv 9 0, 82320), (.priv 10 0, 109830), (.hall 7 1, 84105), (.hall 7 2, 10010), (.hall 0 3, 2439360), (.hall 1 3, 221760), (.hall 6 3, 22710), (.hall 0 4, 1040760), (.hall 5 5, 17340), (.hall 4 8, 57680), (.hall 3 11, 1399860), (.hall 1 13, 2162160)],
  .gen .cond 1800000 [(.count 2, 305945640), (.count 3, 79085160), (.count 4, 24365880), (.count 5, 8933400), (.count 6, 4029480), (.count 7, 2598960), (.count 8, 2598960), (.path 9, 628380), (.priv 10 0, 300090), (.hall 8 1, 260400), (.hall 7 2, 58450), (.hall 8 2, 27944), (.hall 0 3, 2356200), (.hall 7 3, 55209), (.hall 6 4, 78972), (.hall 0 5, 171360), (.hall 5 6, 51375), (.hall 5 8, 434840), (.hall 4 9, 940464), (.hall 3 11, 6590430), (.assumption 9, 2598680)]]

/-- The check items of `(n, a) = (30, 16)`. -/
def items_30_16 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1572480000 [(.count 2, 244497052800), (.count 3, 48281032800), (.count 4, 11891880000), (.count 5, 3805401600), (.count 6, 1614412800), (.count 7, 1576575000), (.path 8, 45252480), (.path 9, 490253400), (.priv 5 7, 320864544), (.priv 6 4, 101244000), (.priv 6 5, 213012800), (.priv 6 6, 205645440), (.priv 7 2, 149324175), (.priv 7 3, 37323000), (.priv 8 0, 82082000), (.priv 9 0, 61261200), (.hall 4 8, 16401840), (.hall 5 10, 60933600), (.hall 3 11, 309493800)],
  .gen .cond 320320000 [(.count 2, 82482079680), (.count 3, 21476735280), (.count 4, 6002156160), (.count 5, 2144862720), (.count 6, 922521600), (.count 7, 557476920), (.count 8, 524684160), (.path 9, 128124360), (.priv 3 13, 1593511920), (.priv 6 5, 33713680), (.priv 6 6, 154426272), (.priv 7 3, 36241920), (.priv 7 4, 108108000), (.priv 7 5, 146017872), (.priv 8 1, 32612580), (.priv 8 2, 70785000), (.priv 9 0, 48348300), (.priv 10 0, 45714240), (.hall 5 6, 3399552), (.hall 5 7, 7456176), (.hall 4 9, 61667424), (.hall 3 11, 270616500), (.assumption 9, 557129664)],
  .gen .cond 2108383200000 [(.count 2, 311508557680320), (.count 3, 89002445051520), (.count 4, 27562471896960), (.count 5, 9587661763680), (.count 6, 3837257424000), (.count 7, 2570962474080), (.count 9, 953832559680), (.count 11, 2080341703440), (.path 7, 764891127000), (.priv 2 14, 12843848777760), (.priv 6 6, 1064564845344), (.priv 7 4, 454760686380), (.priv 7 5, 1432667468232), (.priv 8 1, 120085600635), (.priv 8 2, 19577844000), (.priv 8 3, 876859003020), (.priv 8 4, 535297410648), (.priv 9 1, 514244702400), (.priv 10 0, 156935997504), (.hall 6 7, 53142969880), (.hall 5 8, 459374531616), (.hall 6 8, 516750666432), (.hall 4 9, 657965061936), (.hall 3 11, 3537392623380), (.hall 2 13, 35068617286560), (.assumption 10, 961019803744)]]

/-- The check items of `(n, a) = (30, 17)`. -/
def items_30_17 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .gen .pos 1102464000000 [(.count 2, 150379323494400), (.count 3, 23174895744000), (.count 4, 4747342279680), (.count 5, 1498175078400), (.count 6, 1100222323200), (.path 7, 400891491000), (.path 8, 150346022400), (.priv 5 8, 338337871872), (.priv 6 6, 81931449600), (.priv 7 3, 22363941600), (.priv 8 0, 15020765760), (.hall 6 2, 1884879360), (.hall 4 8, 515106816), (.hall 3 10, 5787936000)],
  .gen .pos 151200000 [(.count 2, 38945907000), (.count 3, 8043235200), (.count 4, 1835673840), (.count 5, 504504000), (.count 6, 191891700), (.count 7, 151351200), (.path 8, 40321800), (.path 9, 20160000), (.priv 3 14, 918918000), (.priv 7 10, 457528500), (.priv 8 0, 5180175), (.priv 9 0, 2242240), (.hall 6 4, 1237860), (.hall 8 4, 2779920), (.hall 9 4, 6764472), (.hall 7 5, 1720290), (.hall 5 6, 136500), (.hall 5 10, 66448200), (.hall 4 11, 76424040)],
  .gen .cond 10192000000 [(.count 2, 4530092767200), (.count 3, 1051588137600), (.count 4, 298585647360), (.count 5, 90810720000), (.count 6, 36778341600), (.count 7, 20886465600), (.count 8, 18767548800), (.path 9, 5189123520), (.priv 4 11, 36732936240), (.priv 5 8, 8076100032), (.priv 5 9, 17011874880), (.priv 5 10, 27949521600), (.priv 6 6, 7498190700), (.priv 6 7, 10488638160), (.priv 6 8, 8977018050), (.priv 7 3, 689188500), (.priv 7 4, 4832427600), (.priv 7 5, 4589184600), (.priv 8 1, 1063662600), (.priv 8 2, 2208781575), (.priv 9 0, 1318437120), (.priv 10 0, 1277025750), (.hall 4 12, 12615704640), (.hall 3 13, 84064780800), (.hall 2 14, 72588035520), (.assumption 9, 20943936720)],
  .gen .cond 7980336000000 [(.count 2, 2057930742067200), (.count 3, 589063713638400), (.count 4, 178488833402880), (.count 5, 58709735884800), (.count 6, 21489448780800), (.count 7, 8743256121600), (.count 8, 4634979148800), (.count 9, 5309157934080), (.count 11, 6952468723200), (.path 7, 3360110153400), (.priv 2 15, 110080754784000), (.priv 4 10, 9006607209600), (.priv 4 11, 40893156944640), (.priv 5 8, 7045168306176), (.priv 5 9, 19761865643520), (.priv 5 10, 35263295907840), (.priv 6 6, 3991232044800), (.priv 6 7, 8216553945600), (.priv 6 8, 23508473788800), (.priv 6 9, 7806896697600), (.priv 7 4, 1979970220800), (.priv 7 5, 6089680396800), (.priv 7 6, 9694329765120), (.priv 8 2, 768107340000), (.priv 8 3, 3872515046400), (.priv 8 4, 2080473595200), (.priv 9 1, 2124365443200), (.priv 10 0, 600440480640), (.hall 4 12, 46751705763840), (.hall 3 13, 146995053004800), (.hall 2 14, 232675953269760), (.assumption 10, 5355692160000)]]

/-- The check items of `(n, a) = (30, 18)`. -/
def items_30_18 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .gen .pos 39600000 [(.count 2, 13210797600), (.count 3, 2905943040), (.count 4, 677476800), (.count 5, 176576400), (.count 6, 57142800), (.count 7, 39639600), (.path 8, 17599680), (.hall 8 2, 176176), (.hall 8 3, 66066), (.hall 7 7, 182910)],
  .gen .pos 80000 [(.count 2, 45765720), (.count 3, 12324312), (.count 4, 3363360), (.count 5, 930930), (.count 6, 321750), (.count 7, 135135), (.count 8, 104104), (.path 8, 26664)],
  .gen .cond 832314000000 [(.count 2, 560445623337600), (.count 3, 123143786045280), (.count 4, 31192997996160), (.count 5, 8033910885000), (.count 6, 2172981610800), (.count 7, 642712870800), (.count 8, 399910230720), (.path 6, 1063134072000), (.priv 2 16, 16067821770000), (.priv 3 13, 5298810557040), (.priv 3 14, 17867417808240), (.priv 4 11, 6298586133840), (.priv 4 12, 8740895042880), (.priv 4 13, 11254616493120), (.priv 5 8, 722456875140), (.priv 5 9, 3239272868832), (.priv 5 10, 4825702471590), (.priv 5 11, 5565417377520), (.priv 6 6, 664573852800), (.priv 6 7, 1724102780400), (.priv 6 8, 2676950115840), (.priv 6 9, 1154077674750), (.priv 7 4, 422736739425), (.priv 7 5, 1111995284400), (.priv 7 6, 861201240900), (.priv 8 2, 206302896800), (.priv 8 3, 621289108440), (.priv 9 0, 42847524720), (.priv 9 1, 212650678240), (.priv 10 0, 61890869040), (.hall 3 14, 3239272868832), (.hall 2 15, 14809175731350), (.assumption 10, 644410791360)],
  .gen .neg 104454236880000 [(.count 2, 104011002734839200), (.count 3, 14787586315101600), (.count 4, 2602349645575680), (.count 5, 269695036611000), (.path 4, 827088832009440), (.path 5, 268693936711200), (.priv 2 16, 9883285803190800), (.priv 3 6, 106550285233392), (.priv 3 13, 2696950366110000), (.priv 3 14, 3691917593484120), (.priv 4 10, 503541379124784), (.priv 4 11, 1314452116897920), (.priv 4 12, 1801839454855440), (.priv 4 13, 2233074903139080), (.priv 5 7, 44692320352680), (.priv 5 8, 308697088059360), (.priv 5 9, 592831182015072), (.priv 5 10, 839581394742090), (.priv 5 11, 1298685330142200), (.priv 6 5, 34082339791500), (.priv 6 6, 154280802733200), (.priv 6 7, 307235005077000), (.priv 6 8, 462927084820200), (.priv 6 9, 393132380290650), (.priv 7 3, 17057634794200), (.priv 7 4, 80167590553050), (.priv 7 5, 180530555119200), (.priv 7 6, 266632565499300), (.priv 8 1, 10206919847124), (.priv 8 2, 42321374975880), (.priv 8 3, 121155308754480), (.priv 8 4, 36986747878080), (.priv 9 0, 46802461738032), (.priv 9 1, 26370181357520), (.priv 10 0, 27107808808080), (.priv 11 0, 9335597421150), (.hall 3 14, 805599820129104), (.hall 2 15, 3578645678107500)]]

/-- The check items of `(n, a) = (30, 19)`. -/
def items_30_19 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .gen .pos 1584140000 [(.count 2, 2437402159920), (.count 3, 482060138560), (.count 4, 99756464080), (.count 5, 24506645800), (.count 6, 5972207800), (.count 7, 1441567400), (.count 8, 1729880880), (.path 3, 24456031600), (.path 6, 2772437250)],
  .gen .cond 61775280000 [(.count 2, 54434276376480), (.count 3, 12349743325920), (.count 4, 2906341598160), (.count 5, 744568624800), (.count 6, 195607011600), (.count 7, 53003190240), (.path 6, 92197516950), (.priv 2 17, 5061804667920), (.priv 3 13, 14723108400), (.priv 3 14, 1849222415040), (.priv 3 15, 2167241556480), (.priv 4 11, 389131755012), (.priv 4 12, 1021415645250), (.priv 4 13, 1136623968480), (.priv 4 14, 812715583680), (.priv 5 8, 30648103200), (.priv 5 9, 332742249840), (.priv 5 10, 521702829648), (.priv 5 11, 592184452860), (.priv 6 6, 46272626400), (.priv 6 7, 213785543400), (.priv 6 8, 327589161900), (.priv 6 9, 9254525280), (.priv 7 4, 42626904320), (.priv 7 5, 150964443630), (.priv 7 6, 26681878080), (.priv 8 2, 33568687152), (.priv 8 3, 39261622400), (.priv 9 0, 14990801280), (.priv 9 1, 4711394688), (.priv 10 0, 5300319024), (.hall 2 16, 1219073375520), (.assumption 10, 55566864360)],
  .gen .cond 2046945600000 [(.count 2, 2610475045738560), (.count 3, 480361909547520), (.count 4, 85755216587040), (.count 5, 12084874401600), (.count 6, 592395804000), (.path 5, 10938983655600), (.priv 2 17, 251294300056800), (.priv 3 13, 5307866403840), (.priv 3 14, 81755886692480), (.priv 3 15, 103226943499680), (.priv 4 11, 18129681185616), (.priv 4 12, 42628802055840), (.priv 4 13, 53009551194600), (.priv 4 14, 54260493667380), (.priv 5 8, 1770417174240), (.priv 5 9, 12112519539120), (.priv 5 10, 20961333128736), (.priv 5 11, 28233584018640), (.priv 5 12, 14849388153600), (.priv 6 6, 1648834987800), (.priv 6 7, 6877433191200), (.priv 6 8, 12305377284200), (.priv 6 9, 12211252173120), (.priv 7 4, 1021553653120), (.priv 7 5, 4386690928620), (.priv 7 6, 7795928780640), (.priv 8 2, 609575282316), (.priv 8 3, 3312808979480), (.priv 8 4, 1067793436710), (.priv 9 0, 613219414080), (.priv 9 1, 1061573280768), (.priv 10 0, 547373722896), (.hall 2 16, 65743389391680), (.assumption 11, 628801218864)],
  .gen .neg 2251839168600000 [(.count 2, 4293850161998517120), (.count 3, 586578882821611680), (.count 4, 76896704665020240), (.count 5, 13248534902803200), (.count 6, 1380055719042000), (.path 3, 177484856367218400), (.path 5, 5326558386949800), (.path 6, 1304353633482900), (.priv 10 2, 144905850499410), (.hall 8 5, 120441226389120), (.hall 9 5, 133405386174060), (.hall 6 6, 117674681124840), (.hall 7 6, 125459610822000), (.hall 5 9, 235340171069400), (.hall 4 11, 769292598255720), (.hall 3 12, 615398692560498)]]

/-- The check items of `(n, a) = (30, 20)`. -/
def items_30_20 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 10769119200000 [(.count 2, 21335554961360640), (.count 3, 3790208733030720), (.count 4, 687448877955840), (.count 5, 117038787465600), (.count 6, 22175770256640), (.count 7, 12935865983040), (.path 5, 75753394516800), (.priv 2 18, 1362577883546880), (.priv 3 14, 284050057210920), (.priv 3 15, 615890952636960), (.priv 3 16, 570256092085680), (.priv 4 11, 84083128889760), (.priv 4 12, 270174800960064), (.priv 4 13, 323627647182840), (.priv 4 14, 179562139716960), (.priv 5 8, 12935865983040), (.priv 5 9, 91871048206080), (.priv 5 10, 164162299260960), (.priv 5 11, 95848606998144), (.priv 6 6, 19095802165440), (.priv 6 7, 76460207864040), (.priv 6 8, 43207552365120), (.priv 7 4, 21898573128432), (.priv 7 5, 26077063172160), (.priv 8 2, 14503849738560), (.priv 9 0, 3593296106400), (.hall 2 17, 110194413929600), (.assumption 10, 10595447356725)],
  .gen .cond 24670800000 [(.count 2, 68831216213760), (.count 3, 8675518892040), (.count 4, 863635893120), (.count 5, 31751319600), (.count 6, 12700527840), (.path 3, 622242621000), (.path 4, 804156837120), (.priv 2 18, 4692139452000), (.priv 3 14, 978558030450), (.priv 3 15, 1845574851120), (.priv 3 16, 1910194666380), (.priv 4 11, 247483896660), (.priv 4 12, 744885957816), (.priv 4 13, 948041484390), (.priv 4 14, 944072569440), (.priv 5 8, 27958800870), (.priv 5 9, 211776261840), (.priv 5 10, 420998978400), (.priv 5 11, 536244508800), (.priv 5 12, 78143525460), (.priv 6 6, 26106640560), (.priv 6 7, 159814975320), (.priv 6 8, 279814803840), (.priv 6 9, 56329192920), (.priv 7 4, 23601814236), (.priv 7 5, 139117818840), (.priv 7 6, 39159960840), (.priv 8 2, 27614026440), (.priv 8 3, 45439666272), (.priv 9 0, 23049106080), (.priv 10 0, 8082154080), (.hall 2 17, 531227016320), (.assumption 11, 11623647420)],
  .gen .neg 73166662800000 [(.count 2, 252999666896296320), (.count 3, 38632963758348960), (.count 4, 5264897455097280), (.count 5, 508194735048000), (.path 4, 1243859113486080), (.path 5, 512165195942400), (.priv 4 13, 6664973950154520), (.priv 5 9, 243933472823040), (.priv 5 11, 3331724682974688), (.priv 5 14, 1761741748166400), (.priv 6 6, 6023048711680), (.priv 6 7, 4234956125400), (.priv 7 4, 508194735048), (.hall 8 4, 1054033524544), (.hall 6 5, 5731786771920), (.hall 7 5, 5242526883440), (.hall 9 6, 2771971282080), (.hall 5 7, 3730710067392), (.hall 8 7, 6587709528400), (.hall 4 11, 4743150860448), (.hall 3 13, 21351652324002), (.hall 2 15, 211581729559200)]]

/-- The check items of `(n, a) = (30, 21)`. -/
def items_30_21 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 183 [(.assumption 11, 223)],
  .gen .cond 504 [(.assumption 12, 359)],
  .direct 2]

/-- The check items of `(n, a) = (30, 22)`. -/
def items_30_22 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 745 [(.assumption 11, 1062)],
  .gen .cond 4 [(.assumption 12, 3)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 23)`. -/
def items_30_23 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 247 [(.assumption 12, 222)],
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 24)`. -/
def items_30_24 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 11 [(.assumption 12, 27)],
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 25)`. -/
def items_30_25 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .gen .cond 10 [(.assumption 13, 7)],
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 26)`. -/
def items_30_26 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 27)`. -/
def items_30_27 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 28)`. -/
def items_30_28 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

/-- The check items of `(n, a) = (30, 29)`. -/
def items_30_29 : List TItem :=
  [.direct 1,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 0,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 1,
  .direct 2,
  .direct 2,
  .direct 2,
  .direct 2]

end ZhangKernel

end Erdos993Lean
